### ISSUE TITLE
rbenv: command not found

### ISSUE THREAD

**Issue by daBee** [rbenv/rbenv#1016]
/home/rich/.bash_profile: line 6: rbenv: command not found

    env: bash: No such file or directory

Fresh install of rbenv, using 2.4.1 as global.  

in my .bash_profile:

    export PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"

Passenger is reporting this issue.  

I'm not sure if this is related, but open() nginx.pid has no permissions, even after setting to 755:

    nginx: the configuration file /usr/local/etc/nginx/nginx.conf syntax is ok
    nginx: [emerg] open() "/var/run/nginx.pid" failed (13: Permission denied)
    nginx: configuration file /usr/local/etc/nginx/nginx.conf test failed

**Comment by mislav** [comment]
```
/home/rich/.bash_profile: line 6: rbenv: command not found

env: bash: No such file or directory
```

When do these errors appear? When you launch a new terminal window? Or is rbenv in your normal shell fine, but errors out within Passenger?

Is rbenv installed to `/home/rich/.rbenv/bin`?

**Comment by daBee** [comment]
Passenger error on nginx.  shell is fine.  There is no /home/rich/.rbenv/bin directory

In a couple of hours I am redoing the whole server OS re-install with FreeBSD 11.1 RC1

**Comment by mislav** [comment]
If there is no `/home/rich/.rbenv/bin`, when is rbenv installed then?

It's been a while since I've worked with Passenger. I'm not sure how to configure it for rbenv.

**Comment by mislav** [comment]
Also please see https://github.com/rbenv/rbenv/wiki/How-to-edit-path and https://github.com/rbenv/rbenv/wiki/Deploying-with-rbenv.

**Comment by daBee** [comment]
rbenv is indeed installed at that location.  The /bin/ directory is not.  

    [Thu Jul 06 02:57:01 rich@neb ~/.rbenv] pwd
    /home/rich/.rbenv
    [Thu Jul 06 02:57:16 rich@neb ~/.rbenv] ll
     total 19
     drwxr-xr-x  4 rich  rich   5 Jul  6 07:51 .
     drwxr-xr-x  6 rich  rich  29 Jul  6 12:05 ..
     drwxr-xr-x  2 rich  rich  15 Jul  6 14:22 shims
    -rw-r--r--  1 rich  rich   6 Jul  6 07:51 version
    drwxr-xr-x  3 rich  rich   3 Jun 21 08:53 versions

in .bash_profile:

    export PATH="$HOME/.rbenv/bin:$PATH"

**Comment by mislav** [comment]
> rbenv is indeed installed at that location. The /bin/ directory is not.

Okay, that looks like rbenv is installed elsewhere, but its RBENV_ROOT directory (the place where Ruby versions, plugins, and global version configuration are kept: by default `$HOME/.rbenv`) is still in its default place.

If you execute `which -a rbenv` in your shell, you can locate where the `rbenv` executable actually is on your system. Then, you should ensure that that directory is also present in PATH for the nginx/Passenger process.

Finally, you can remove `export PATH="$HOME/.rbenv/bin:$PATH"` from your `.bash_profile`, since it's not useful since there is no `$HOME/.rbenv/bin` directory.

**Comment by mislav** [comment]
> rbenv is indeed installed at that location. The /bin/ directory is not.

Okay, that looks like rbenv is installed elsewhere, but its RBENV_ROOT directory (the place where Ruby versions, plugins, and global version configuration are kept: by default `$HOME/.rbenv`) is still in its default place.

If you execute `which -a rbenv` in your shell, you can locate where the `rbenv` executable actually is on your system. Then, you should ensure that that directory is also present in PATH for the nginx/Passenger process.

Finally, you can remove `export PATH="$HOME/.rbenv/bin:$PATH"` from your `.bash_profile`, since it's not useful since there is no `$HOME/.rbenv/bin` directory.

**Comment by daBee** [comment]
Sorry for the delay.  Third machine, third FreeBSD OS, same issues.  So, rbenv is installed in ~/

    /usr/home/rich/.rbenv
    /usr/home/rich/.rbenv/shims
    /usr/home/rich/.rbenv/shims/bundle
    /usr/home/rich/.rbenv/shims/bundler
    /usr/home/rich/.rbenv/shims/erb
    /usr/home/rich/.rbenv/shims/filewatcher
    /usr/home/rich/.rbenv/shims/gem
    /usr/home/rich/.rbenv/shims/irb
    /usr/home/rich/.rbenv/shims/rake
    /usr/home/rich/.rbenv/shims/rdoc
    /usr/home/rich/.rbenv/shims/ri
    /usr/home/rich/.rbenv/shims/ruby
    /usr/home/rich/.rbenv/version
    /usr/home/rich/.rbenv/versions
    /usr/home/rich/.rbenv/versions/2.4.1
    /usr/home/rich/.rbenv/versions/2.4.1/bin

The executable:
    /usr/local/bin/rbenv

The only instructions provided for rbenv installation are the following:

    export PATH="$HOME/.rbenv/bin:$PATH"    # in ~/.bash_profile
    eval "$(rbenv init -)"      # also in ~/.bash_profile

The latter of those two resolving to this:

    export PATH="/home/rich/.rbenv/shims:${PATH}"
    export RBENV_SHELL=bash
    source '/usr/local/share/rbenv/completions/rbenv.bash'
    command rbenv rehash 2>/dev/null
    rbenv() {
      local command
      command="$1"
      if [ "$#" -gt 0 ]; then
        shift
      fi
    
      case "$command" in
      rehash|shell)
        eval "$(rbenv "sh-$command" "$@")";;
      *)
        command rbenv "$command" "$@";;
      esac
    }

**Comment by daBee** [comment]
OK, that did it.  Now I'm into ISEs, so I'm moving forward.
