### ISSUE TITLE
ERROR:  While executing gem ... (Gem::FilePermissionError)    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.

### ISSUE THREAD

**Issue by csanch111** [rbenv/rbenv#1035]
To check that I can install the correct version of Rails I run this on my terminal:
$ gem install rails -v 4.2.6

I ran that code in my terminal but it gave me an error of
ERROR:  While executing gem ... (Gem::FilePermissionError)    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.

One solution I thought of since "You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory" is to just modify my user account's permission for that file from "Read" to "Read & Write" to solve this problem. Is this safe to do and will this solve my problem?

**Comment by NALAWALAMURTUZA** [comment]
not found directory like /Library/Ruby

**Comment by mislav** [comment]
Sorry for late reply.

If you're using rbenv, first select a default Ruby version using `rbenv global <VERSION>` (where `<VERSION>` is one of the available ones listed with `rbenv versions`), and then try the `gem install` command again.

The permissions problem was because you tried to `gem install` using the system version of Ruby, which will need sudo permissions to install new gems. But, you don't want to be using the system version of Ruby when you're using rbenv.
