### ISSUE TITLE
Closing terminal does not unset version

### ISSUE THREAD

**Issue by arjunmenon** [rbenv/rbenv#1047]
Hey
Need to confirm if I close the terminal and later start a new session, does rbenv revert back to the globally set ruby version?

Recently I forget to unset the local version for a test run. I had closed my comp.   But when I came back to my terminal and checked for some reason, it still showed the local version which I had set, that too in all terminal windows?

I had to unset from a specific folder (viewed from `rbenv version`) for it to get back to my global setting.

Is this the default behaviour? Should it not _just like that_ revert to the global setting if a session is closed?

Globally it was set to use `2.3.3` and locally for a session as `2.2.3`.

**Comment by mislav** [comment]
A "local" version setting (set by e.g. `rbenv local 2.2.3`) is not local to your terminal session, but **to the current directory** (usually the project root directory) by writing to a `.ruby-version` file in the current directory. That's why the value is persisted between terminal resets.

To set the version that only persists in the current shell session until you close it, see `rbenv shell --help`.
