### ISSUE TITLE
Issues with $PWD and realpath

### ISSUE THREAD

**Issue by zachriggle** [rbenv/rbenv#1048]
Some of the code in `rbenv` which attempts to re-implement `realpath` in native bash has issues when the environment variable `$PWD` is the literal string `/proc/self/cwd`.

This manifests in all kinds of odd ways, and also was copied by the `pyenv` project.

I have submitted a fix to `pyenv` here: pyenv/pyenv#1036

Since I don't use `rbenv`, I'll leave it up to the maintainers whether to cherry-pick this fix.

**Comment by mislav** [comment]
Thank you for reporting!

Personally I'm not motivated to fix this, as it doesn't seem to be a pressing issue. I can't fathom a real-world use where the user would be putting their Ruby application in a directory literally under `/proc/self/cwd`. This sounds more like a theoretical bug rather than one which is giving somebody trouble.

I would accept a PR that improves our `realpath` implementation if the diff isn't too large, and if the result yields a tangible benefit. But since neither of us are motivated right now to make such a change, and since cherry-picking from pyenv isn't a trivial operation, I'm going to go ahead and close this.

**Comment by zachriggle** [comment]
Re: Why this happens in practice, the Android AOSP build process executed
the compilers with that environment variable set on Linux.

The project uses python wrappers, which is why the issue cropped up for
PyEnv.
