### ISSUE TITLE
Jruby executable not added to path correctly on Ubuntu

### ISSUE THREAD

**Issue by ecdemis123** [rbenv/rbenv#1102]
It appears that the jruby executable is not added to the shim/path correctly on Ubuntu.

Example:
```bash
$ cat /proc/version
> Linux version 3.13.0-107-generic (buildd@lcy01-09) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) ) #154-Ubuntu SMP Tue Dec 20 09:57:27 UTC 2016
$ rbenv version
> jruby-9.1.8.0 (set by RBENV_VERSION environment variable)
$ rbenv which jruby
> /home/user/.rbenv/versions/jruby-9.1.8.0/bin/jruby
$ jruby
> The program 'jruby' is currently not installed. To run 'jruby' please ask your administrator to install the package 'jruby'
```

My workaround has been:
```
$ export PATH=$PATH:/home/user/.rbenv/versions/jruby-9.1.8.0/bin
```

I'm not sure how I would debug something like this. From the documentation it seems like the executable is in the correct place which would get added to the path as a shim. Any insights?

**Comment by mislav** [comment]
Hi sorry for the late reply. This sounds like a problem of  rbenv not being setup fully. Please see README for installation instructions and for the doctor script to troubleshoot an installation, and ensure:

1. `rbenv version` lists "jruby-9.1.8.0";
2. run `rbenv rehash` just in case';
3. `which -a jruby` should list `/home/user/.rbenv/shims/jruby` first.

Closing since it's most likely an issue with installation
