### ISSUE TITLE
Please don't install .rbenv in $HOME

### ISSUE THREAD

**Issue by Tucanix** [rbenv/rbenv#1146]
Just to get the ball rolling. It's a bad convention. I'm not a dev on this project, just a user.

Recent conversation on this topic: https://news.ycombinator.com/item?id=19063727

I successfully just used $RBENV_ROOT to install .rbenv in another location, so I assume it wouldn't be a big deal technically to change it by default to something more sane.

**Comment by jasonkarns** [comment]
```
$ rbenv root
/usr/local/var/rbenv
```
I also do not install in `HOME`.

Everything within rbenv (and all properly written plugins) relies on `rbenv root` (or `$RBENV_ROOT`). So yes, it's trivial to install rbenv outside of `HOME`. (Indeed, I ran a campaign a few years back to update the installation directions for a whole bunch of plugins to use `$(rbenv root)/plugins` instead of hardcoding `~/.rbenv` in the README. In some small way, I believe this helps illuminate the fact that rbenv doesn't _have_ to be installed in `HOME`.

But I also don't think that changing the default would be a net positive. The majority of users don't care about their `HOME` and they want simple, easy to follow (and understand) directions. Changing the default would likely cause nothing but confusion and an increase in github issues that we need to triage.

rbenv already has the facility to be installed in a custom location. I think that's sufficient.

**Comment by mislav** [comment]
@Tucanix Where do you think would be a better default location for RBENV_ROOT other than `$HOME/.rbenv`? Or are you basically asking for rbenv to support XDG Base Directory spec? If the latter, should rbenv store its files in `XDG_DATA_HOME`, `XDG_CONFIG_HOME`, or spread them across both, respectively?

**Comment by chpatton013** [comment]
`XDG_DATA_HOME` seems like a good candidate for the rbenv repo and installed ruby versions, and `XDG_CONFIG_HOME` seems like a good candidate for the active global/local version files.

Of course, as was said previously, there's nothing stopping anyone from doing this without upstream support.

**Comment by shamca65** [comment]
A (hopefully) related question. I've been installing rbenv as root in docker containers..it ends up in /root/.rbenv/....

A rails user is then created with home directory  /home/rails and the repo to be tested is cloned into it along with the gems etc.

Is the installation of rbenv under /root 'correct', or should it be installed in rails user's home directory, the same as the repo?

**Comment by mislav** [comment]
@shamca65 Your question is purely an organizational one and as such is kind of off-topic for this thread. We can't really tell you how to install and organize Ruby versions across user accounts; you will have to decide those things yourself.

All you need to know is that rbenv looks up installed Ruby versions under `RBENV_ROOT` and that the deafult value of `RBENV_ROOT` is `$HOME/.rbenv`. Of course, the value of `$HOME` is different for different users. Therefore, to ensure both `rails` and the `root` user look up Ruby versions under the same location, you can keep them under `/root/.rbenv` and make sure that the `rails` user has has `RBENV_ROOT` set to `/root/.rbenv` explicitly so it all works out in the end.

**Comment by shamca65** [comment]
Thanks @mislav - that answers my question indirectly. Have a great Monday.

**Comment by apotheon** [comment]
I think the default and the means of changing `RBENV_ROOT` are fine the way they are and, if anything needs to change, it would be more clarity in documentation for people who don't realize they can change it, if that turns out to be an actual problem.  The XDG Base Directory Specification is effectively a Linux-specific, largely uncurated specification repository that, itself, does not appear to have internal standards for how to compose a specification.  Even that does not apply to all Linux distributions.  Treating it like a standard just makes it more difficult to build configurable cross-platform software.

The "proper" way to (conditionally) use XDG BDS specifications without user intervention would probably be to detect whether there is an environment variable mandating the use of XDG BDS specifications for defining the root directory for rbenv.  That environment variable could, then, be used to do the same with multiple other pieces of software, without breaking cross-platform compatibility with (other) Unix-like systems and their conventions.

**Comment by mislav** [comment]
Closed in favor of RBENV_ROOT for customization.
