### ISSUE TITLE
Unable to serve app ruby 2.5.3?

### ISSUE THREAD

**Issue by missamii** [rbenv/rbenv#1161]
Not sure if anyone else has encountered this already with serving ruby 2.5.3 app. I am trying to serve an app that uses ruby 2.5.3. I get the following from terminal

```
$ rails server
Traceback (most recent call last):
	4: from bin/rails:3:in `<main>'
	3: from bin/rails:3:in `load'
	2: from /Users/tiffanylo/CHAYN/SoulMedicine/soulmedicine/bin/spring:8:in `<top (required)>'
	1: from /Users/tiffanylo/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/Users/tiffanylo/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler (LoadError)
```

**Comment by ultrasam** [comment]
I am also having issues with Rails Server. Are you using raspbian? Ubuntu?

**Comment by Pauloparakleto** [comment]
Hi @missamii and @ultrasam, how is it going?
According to your logFile, your ruby version compiled is 2.5.3, while your bundle is trying to use ruby version 2.5.0. Taking a little close to the beggining of the rbenv official documentation (how rbenv works), there is a priority in searching the versions path, first local and after global.
It's seems your bundle is searching the global path instead of the local one. Try remove (uninstalling) the global one to avoid bundle to find this path.
Checking your ruby versions:
`rbenv local` - this will say the first path reached.
`rbenv global` this may say _system_, meaning the global ruby version.

**Comment by mislav** [comment]
This issue tracker is for a Ruby version manager. Please ask questions about general Ruby usage elsewhere, in more appropriate support forums. Thank you!
