### ISSUE TITLE
ruby 2.1.2 install fails on ArchLinux

### ISSUE THREAD

**Issue by noraj** [rbenv/rbenv#1164]
## Description

ruby 2.1.2 install fails on ArchLinux

```
$ rbenv install 2.1.2
Downloading ruby-2.1.2.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.2.tar.bz2
Installing ruby-2.1.2...

WARNING: ruby-2.1.2 is past its end of life and is now unsupported.
It no longer receives bug fixes or critical security updates.


BUILD FAILED (Arch Linux using ruby-build 20190401)

Inspect or clean up the working tree at /tmp/ruby-build.20190517165312.6120
Results logged to /tmp/ruby-build.20190517165312.6120.log

Last 10 log lines:
compiling callback-8.c
linking shared-object pathname.so
make[2]: Leaving directory '/tmp/ruby-build.20190517165312.6120/ruby-2.1.2/ext/pathname'
installing default callback libraries
linking shared-object nkf.so
make[2]: Leaving directory '/tmp/ruby-build.20190517165312.6120/ruby-2.1.2/ext/nkf'
linking shared-object dl/callback.so
make[2]: Leaving directory '/tmp/ruby-build.20190517165312.6120/ruby-2.1.2/ext/dl/callback'
make[1]: Leaving directory '/tmp/ruby-build.20190517165312.6120/ruby-2.1.2'
make: *** [uncommon.mk:180: build-ext] Error 2
```

Seems totally unrelated to #610.

Here is the full logs: https://pastebin.com/Y5Z70fBW (as you can read, using gcc version 8.3.0)

**Comment by mislav** [comment]
It looks like you're having problems with [ruby-build](https://github.com/rbenv/ruby-build), which is the plugin that provides the `rbenv install` command.

1. First, [ensure that ruby-build is updated](https://github.com/rbenv/ruby-build/wiki#updating-ruby-build) to the latest version.
2. If your problem persists, [check existing issues in the ruby-build repo](https://github.com/rbenv/ruby-build/issues) and open a new one if necessary. When opening a new issue, please attach the full build log.

Ultimately, since 2.1.2 is EOL, it might not be possible for you to install it on Arch linux in a straightforward way.
