### ISSUE TITLE
Question: In each file in the `.rbenv/shims` directory, why is this conditional only executed if the running program is `ruby`?

### ISSUE THREAD

**Issue by richiethomas** [rbenv/rbenv#1173]
I hope this is the correct place to post this question.  I did initially ask this [on StackOverflow](https://stackoverflow.com/questions/57320421/in-each-file-in-the-rbenv-shims-directory-why-is-this-conditional-only-execu) but didn't receive an answer.

I'm learning about bash scripting now, and studying the shims in my `.rbenv/shims` folder.  I noticed each of the shim files are identical, and in particular, they each include a conditional block which starts with `if [ "$program" = "ruby" ]; then`.  

I *think* I know what the if conditional does:

- If the name of the program being executed is ruby, then:
- For each argument after ruby:
- break out of the loop if the -e flag or -- is passed as an argument to the Ruby interpreter.
- set the RBENV_DIR environment variable equal to the pathname (minus the filename) if the provided argument is the name of a file which exists on disk

My question is:

1. Why is this logic only needed if the executing program is ruby?
2. More generally, why is the conditional needed? I'm genuinely confused why, for example, you'd want to break out of the loop when the symbols -e or -- are passed.

I know what these flags do (ruby -e lets you evaluate Ruby code in the command line without passing a filename, and -- signifies the end of command options and flags, and the beginning of positional parameters. But perhaps I don't understand these well enough, because I'm confused why these two options (and only these two) would require RBENV to break out of the loop.

3. Lastly, why is this logic included in every shim if, as it appears, it's only needed for the ruby shim?

Thanks in advance for your help.

**Comment by jasonkarns** [comment]
The first place I would look for an explanation of some code is its git history. Assuming good commit messages, it will explain the code's origin and evolution over time, using git blame.

In this case, shims are created by [rbenv-rehash](https://github.com/rbenv/rbenv/blob/master/libexec/rbenv-rehash) so checking its blame around the code that generates shims: https://github.com/rbenv/rbenv/blame/4e923221ce57a04ab52bddd638473d566347711f/libexec/rbenv-rehash#L42-L62 shows the most recent commit here: https://github.com/rbenv/rbenv/commit/283e67b57e8ab0bbbe504aab6866729b0035186a

The commit message:
> When the ruby shim is invoked with a script, set RBENV_DIR to the script's dirname
is talking about special handling for when ruby is invoked with a script name...

Let's re-parse the code with this context:

Instead of looking at `-e`/`--` args, let's look at the behavior for the `*/*` scenario. An argument that contains a `/` is _probably_ indicative of a path/filename. That is we're passing a ruby script as an argument to ruby that we want it to execute. When ruby receives a script name, rbenv ensures that `RBENV_DIR` is set as the directory in which the provided script lives. The PR linked from that commit has much longer discussion around _why_ https://github.com/rbenv/rbenv/pull/299 (which also links to the originating Issue)

Now that we see the real purpose for this code is to handle ruby script args, we can derive the `-e`/`--` case. Firstly, `-e` and a script filename argument are mutually exclusive. Ruby will _either_ execute the script given by the filename, or execute the code given as the argument to the `-e` option; never both. So if `-e` is found, there is no need to continue searching the arguments for a filename and we can exit early. (Indeed, exiting early isn't just an optimization but can prevent bugs wherein the `*/*` pattern would accidentally match the body of a ruby script argument to `-e`. Such as `-e 'require "foo/bar"'`.)

Similarly with `-e`, the `--` flag is the "special" flag that indicates the end of options. (Anything after are raw args, not options.)

I believe this answers your second question. As to the first, why is this only needed for ruby? If a ruby script (call it R1) "shells-out" to ruby again (call it R2) – either directly, or transitively through another executable – then it's desirable for the ruby version for R2 to be set according to the directory of R2's script (say, if that directory or directory tree contains a .ruby-version file). Prior to this behavior, R2's ruby version would always be the same as R1, because the invocation of R1 would have adjusted the `PATH` already such that a ruby were selected. The old workaround was to allow ruby scripts to have special shebang's that would force a re-evaluation of rbenv. That was an suboptimal implementation as one shouldn't need to change their shebangs in order to have rbenv involved. So this shim logic allows the RBENV_DIR variable to be set, which allows rbenv to do its version lookup as if the current working directory were the location of R2, and thus allow R2 to run under its own ruby version, possibly distinct from R1's ruby version.

And lastly Question 3: that was actually even discussed on the PR: https://github.com/rbenv/rbenv/pull/299#issuecomment-11722302 
> My idea was to create a special shim for ruby but you opted for having identical shims across the board and having them embed a conditional.

So when rbenv creates shims, the current implementation means that an identical shim is created for every executable. This makes the shim-creation logic simpler. Of course, as you noted, it also means that every shim needs to do a quick check, even though the program name will always be the same for a given shim. Tradeoffs! The alternative would be having two distinct shim contents. One for ruby and one for everything else. But that would mean the shim creation step would need to "store" two different shim bodies, each of which would be 99% identical. I could see that duplication being a problem as future changes to one shim body being "forgotten" on the other body, etc. But that _could_ have been a valid implementation.


One last note... In doing this quick dive, I've discovered that ruby now (possibly always?) allows a ruby script filename to be given _after_ the `--` flag. So it's possible (I haven't confirmed yet), that this thread has actually uncovered a slight bug! So thank you! :D 

Hopefully this helps.

**Comment by richiethomas** [comment]
@jasonkarns thanks very much for putting in the effort to craft such a thorough and well-thought-out response to my question.  I learned a lot from your answer and appreciate you taking the time to post it.
