### ISSUE TITLE
Export/provide RBENV_ORIG_PATH?

### ISSUE THREAD

**Issue by blueyed** [rbenv/rbenv#1190]
There might be tools interested in the original path (https://github.com/pyenv/pyenv/pull/1169#issuecomment-535693545).

This was included in https://github.com/rbenv/rbenv/pull/1089, but closed for other reasons.

Do you think it makes sense to provide the original PATH in a separate variable?

**Comment by mislav** [comment]
Thanks for the suggestion, but without a compelling reason to provide this specific feature, I'd rather not add it. In general, tools should not be aware that rbenv exists. If they want to be, they are likely doing something wrong.

**Comment by ylecuyer** [comment]
Hello,

Here is an example, we have a project to handle our infra and other projects. This project has rake tasks to check licences, cves in gems and cves in ruby (which known tools like license_audit, bundler_audit and ruby_audit)

Basically we have a cron which runs every day and does `/bin/bash -l -c 'cd dir && bundle exec rake task'`

ruby_audit uses `RUBY_VERSION` `RUBY_PATCHLEVEL` and `RUBY_ENGINE` to do the check hence needs to be run with the project version of ruby for the check to be correct.

The problem is that when invoking with rbenv, the PATH is set with the ruby version of the project managing the infra, later on, using `RBENV_VERSION` or `rbenv shell` to override the change doesn't work (even if `rbenv version` says the contrary)

For the moment the only fix I have was to save the PATH variable before it is modified by rbenv like so: `/bin/bash -l -c 'cd dir && export ORIGINAL_PATH=$PATH && bundle exec rake task'`

Though it would be nice to have it directly from rbenv as suggested in this issue

**Comment by mislav** [comment]
@ylecuyer Sorry for the trouble. Rbenv isn't well-suited for tasks that should run across several different Ruby versions. Refer to https://github.com/rbenv/rbenv/issues/121 for more information
