### ISSUE TITLE
Either documentation or installer fails to setup shims directory correctly

### ISSUE THREAD

**Issue by crowbar27** [rbenv/rbenv#1193]
I have setup rbenv according to the documentation on a fresh CentOS 7.7 machine. The result is that the installation does not work (`ruby` is not found regardless of me adding it as local or global). I finally found out that the `shims` directory never makes it to the path and therefore executed

`echo 'export PATH="$HOME/.rbenv/shims:$PATH"' >> ~/.bash_profile`

which made the stuff work. I am unsure whether the installer or `rbenv init` should do this or the documentation is lacking this step.

**Comment by mislav** [comment]
The installation [instructions say this](https://github.com/rbenv/rbenv#basic-github-checkout):

> 3\. Set up rbenv in your shell.
>
>        $ ~/.rbenv/bin/rbenv init
> Follow the printed instructions
>
> 4\. Restart your shell so that PATH changes take effect

If you had executed `rbenv init`, it would show you something like this:
```sh
# Load rbenv automatically by appending
# the following to ~/.bash_profile:

eval "$(rbenv init -)"
```

And if you had appended that line to your `~/.bash_profile`, it would have worked to insert the shims directory into your PATH.

Your approach was technically correct too. Either the line you added or the line that the install instructions tell you to add was necessary to complete the installation.

**Comment by crowbar27** [comment]
Hi mislav,

thanks for your explanations. I looked into it and I think I now got the problem (which is probably the cause for several issues I stumbled over while troubleshooting that have users complaining about `rbenv init` not working). I believe the documentation is misleading at best for users having no experience with rbenv and just want to use it.

First, from your explanation and from the installation guide, I would assume that `rbenv init` updates the path such that ruby is working, i.e. it includes the shims directory.

Second, I remember the output of `rbenv init` that you quoted and I still think this can only be interpreted as adding this line to `~/.bash_profile` is **optional**, i. e. if I do not want to load rbenv automatically, I do not need to do that, but I can call `rbenv init` on demand.

However, calling `rbenv init` on demand does not work, and I believe I have now understood why: If I add the `eval` line into my `~/.bash_profile`, the stuff is sourced in the shell, whereas if I just call `rbenv init`, it is not. The following ouput from a CentOS 7.7 machine illustrates this effect:

```bash
[root@crabcore ~]# rbenv init
# Load rbenv automatically by appending
# the following to ~/.bash_profile:

eval "$(rbenv init -)"

[root@crabcore ~]# which ruby
/usr/bin/which: no ruby in (/root/.nodenv/bin:/root/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
[root@crabcore ~]# eval "$(rbenv init -)"
[root@crabcore ~]# which ruby
/root/.rbenv/shims/ruby
```

I would therefore suggest hinting users at calling `eval "$(rbenv init -)"` and not `rbenv init` if they want to use rbenv on demand and/or change the output of `rbenv init` telling users that they **must** add the `eval` line.

Best regards,
Christoph

**Comment by mislav** [comment]
@crowbar27 Thanks for the thoughtful reply. Reopening this issue to serve as a TODO item for improving the docs around this

**Comment by ajtran303** [comment]
Hello, I am just posting this here so that someone else can see it and maybe help me?
It might also be something that other people are experiencing... 

I appended `eval "$(rbenv init -)"` into my ~/.zshrc and my shims are not being prepended to my $PATH.

Here is what I get when I run `rbenv init -`

```
export PATH="/Users/ayylmao/.rbenv/shims:${PATH}"
export RBENV_SHELL=zsh
source '/usr/local/Cellar/rbenv/1.1.2/libexec/../completions/rbenv.zsh'
command rbenv rehash 2>/dev/null
rbenv() {
  local command
  command="${1:-}"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "$(rbenv "sh-$command" "$@")";;
  *)
    command rbenv "$command" "$@";;
  esac
}
```

But when I run `which ruby` I just get `/usr/bin/ruby`.


----

Will it be necessary to add to my shell config something similar to the user who opened this thread,
`export PATH="$HOME/.rbenv/shims:$PATH` ?

I am wondering if I should go nuclear and uninstall / reinstall....

**Comment by mislav** [comment]
@ajtran303 Sorry you're having trouble!

1. When you open a new shell/terminal window and do `echo $PATH`, do you see rbenv having inserted the shims path?
2. Do you have any Ruby versions known to rbenv? See `rbenv versions`

You don't need to explicitly add `export PATH="$HOME/.rbenv/shims:$PATH` if you already have `eval "$(rbenv init -)"` in your zsh config.

**Comment by ajtran303** [comment]
@mislav Hi thanks for getting back to me! When I `echo $PATH` it showed no shims, just like `which ruby` showed no different path either. 

I tried a lot of digging and ultimately ended up just re-installing (nuclear, to factory settings) and everything works now.

But I wanted to chime in because it could be that other people may experience the same thing at some point... Thanks again!

**Comment by jpeters-ml** [comment]
I followed the readme, which included adding the eval to the `.zshrc`. I tried to source and reload the terminal to no avail, it wasn't until I added the code below after the eval that the curl command worked successfully.

```
eval "$(rbenv init -)"
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"
```

**Comment by tuffylock** [comment]
Sorry to butt in on what looks like an active conversation, but I've been  trying to clarify something and can't find a straightforward explanation.

>You don't need to explicitly add export PATH="$HOME/.rbenv/shims:$PATH if you already have eval "$(rbenv init -)" in your zsh config.

Why is this the case for homebrew installations when the github checkout installation _does_ (according to the readme) require both lines?

**Comment by mislav** [comment]
@tuffylock The `eval` step in your shell initialization file will add the `shims` directory to your PATH, in addition to doing some other shell setup. That's why it's usually not necessary to add the `shims` directory manually. However, if one wishes to do a complete manual setup of rbenv, without any shell integration, one could omit the `eval` line and configure their PATH manually.

**Comment by chinghoi** [comment]
> ```
> # Load rbenv automatically by appending
> # the following to ~/.zshrc:
> eval "$(rbenv init - zsh)"
> ```
> 
> @jpeters-ml您是否按照这些说明将“eval”行添加到您的 zshrc 中？
> 
> ```
> eval "$(rbenv init - zsh)"
> ```
> 
> 之后重新启动你的 shell 或终端窗口，你的 PATH 应该是：
> 
> ```
> /Users/<user>/.rbenv/shims:/usr/local/sbin: ...
> ```



> ```
> # Load rbenv automatically by appending
> # the following to ~/.zshrc:
> eval "$(rbenv init - zsh)"
> ```
> 
> @jpeters-ml您是否按照这些说明将“eval”行添加到您的 zshrc 中？
> 
> ```
> eval "$(rbenv init - zsh)"
> ```
> 
> 之后重新启动你的 shell 或终端窗口，你的 PATH 应该是：
> 
> ```
> /Users/<user>/.rbenv/shims:/usr/local/sbin: ...
> ```

I forgot that I needed to restart the terminal, thank you.

**Comment by chinghoi** [comment]
> ```
> # Load rbenv automatically by appending
> # the following to ~/.zshrc:
> eval "$(rbenv init - zsh)"
> ```
> 
> @jpeters-ml Have you followed these instructions and added the "eval" line to your zshrc?
> 
> ```
> eval "$(rbenv init - zsh)"
> ```
> 
> After that and restarting your shell or terminal window, your PATH should be:
> 
> ```
> /Users/<user>/.rbenv/shims:/usr/local/sbin: ...
> ```

I forgot that I needed to restart the terminal, thank you.

**Comment by MykolaPylypets** [comment]
My platform:
OS: Debian GNU/Linux 11 (bullseye) x86_64
Kernel: 5.10.0-16-amd64
Shell: bash 5.1.4
On my system no Ruby, nor RVM, nor rbenv were installed before. So I thought it would be a good idea to get Ruby and do it the right way using rbenv.
To cut it short, I failed to do it using instructions. Now I'm stuck. I do not know what to do next. 
When I started reading the instructions the first thing caught my attention... It's the recommendation NOT to use the standard package management system for Debian. Every time they tell me NOT to use apt I feel bad. What happened later only proved my expectations. 
The instructions suggest to do a github checkout. - No problem, I go to corresponding section. Now it suggests to do automatic curl script rather than doing manually. - I ran that. The output seemed ok. I checked my PATH and it didn't contain "rbenv"! Then I consulted the curl script output again. It said to run 'rbenv init'. I ran that - bash: rbenv: command not found. - Ok, I probably ought to restart the terminal. I do a restart but to no avail. 
Now I happened to see some advice and possible ways out like removing rbenv directory and reinstalling, but how can I trust it If I fail to do the OFFICIAL instructions! I do not want to mess with my system. What should I do now?

**Comment by mislav** [comment]
> The instructions suggest to do a github checkout. - No problem, I go to corresponding section. Now it suggests to do automatic curl script rather than doing manually. - I ran that. The output seemed ok. I checked my PATH and it didn't contain "rbenv"! Then I consulted the curl script output again. It said to run 'rbenv init'. I ran that - bash: rbenv: command not found. - Ok, I probably ought to restart the terminal. I do a restart but to no avail.

@MykolaPylypets Thanks for detailing your process, and sorry for the inconvenience.

If you were following the [Basic GitHub Checkout](https://github.com/rbenv/rbenv#basic-github-checkout) procedure, then there is no bare `rbenv init` step. Instead, the invocation contains the full path to the rbenv command:
> ```
> ~/.rbenv/bin/rbenv init
> ```
> Follow the printed instructions…

If you run that exact line, provided that you have executed the previous steps, I guarantee you that it will work and instructions will be printed.

**Comment by mislav** [comment]
Update: the documentation should now be clearer on many topics including installation, which now has fewer steps, should be easier to follow, and hopefully have less pitfalls for the average user. https://github.com/rbenv/rbenv/pull/1433

Thank you to everyone sharing your experience. I will now close this, but feel free to add comments or open new issues if further inconsistencies with the setup process are found.

**Comment by logicalmoody** [comment]
I was stuck in a similar situation on macOS 14.2 with M2, attempting to install rbenv. I would get no shims from `which ruby` but saw the shims in my path. This [comment](https://github.com/rbenv/rbenv/issues/1217#issuecomment-868565280) was able to get me unstuck! Posting here for future hapless devs

> I added these lines at the end of my .zshrc file (for those of us who are using oh my zsh)
> 
> # rbenv configuration
> eval "$(rbenv init -)"
> export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"
