### ISSUE TITLE
rbenv installation issue

### ISSUE THREAD

**Issue by Santhosh-Yabx** [rbenv/rbenv#1205]
Hi Friends,

Please assist me with the below issue while installing  rbenv on ubuntu 14.04.3.
```
$ git clone https://github.com/rbenv/rbenv.git ~/.rbenv
Cloning into '/yabx/.rbenv'...
remote: Enumerating objects: 2788, done.
remote: Total 2788 (delta 0), reused 0 (delta 0), pack-reused 2788
Receiving objects: 100% (2788/2788), 536.25 KiB | 743.00 KiB/s, done.
Resolving deltas: 100% (1746/1746), done.
$ echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
$ echo 'eval "$(rbenv init -)"' >> ~/.bashrc
$ exec $SHELL
$ git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
Cloning into '/yabx/.rbenv/plugins/ruby-build'...
remote: Enumerating objects: 111, done.
remote: Counting objects: 100% (111/111), done.
remote: Compressing objects: 100% (76/76), done.
remote: Total 10239 (delta 69), reused 61 (delta 28), pack-reused 10128
Receiving objects: 100% (10239/10239), 2.17 MiB | 2.02 MiB/s, done.
Resolving deltas: 100% (6657/6657), done.
$ echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc
$ exec $SHELL
$ rbenv install 2.7.0
/bin/sh: 1: rbenv: not found
```

Thanks & Regards,
Santhosh.

**Comment by mislav** [comment]
1. After you `exec $SHELL` for the first time, can you check what is the value of `echo $PATH` and that the rbenv bin directory is listed there?

1. You might want to restart your terminal session instead of `exec $SHELL` for the changes to be picked up.

2. (Minor) You do not need the `echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc` line. Once rbenv works, the `rbenv install` command will work as well without that line.

Closing since this is a usage question. Hope that you can inspect your own environment to figure out what went wrong during the install.

**Comment by webdevotion** [comment]
FWIW I _quickfixed_ the issue by replacing `$HOME` with the name of my user.
So I replaced `$HOME/.rbenv/...` with `/user_on_my_machine/.rbenv/...`. And in stead of relying on `sourcing` or `exporting` the value to `.bashrc` I just set an env variable with that new `$PATH`. 
This is not a long term solution but might help someone to get along with their local dev work.
Using Ubuntu 19.10.
