### ISSUE TITLE
cannot load such file -- tk (LoadError)

### ISSUE THREAD

**Issue by harunasan** [rbenv/rbenv#1211]
Hello, 
I am using a MacBook Pro 16" with macOS Catalina and today I installed rbenv through the guide and I get this error message, when I am running the toolbox:

/bin/zsh -c "bash -c 'env RBENV_VERSION=2.7.0 /usr/local/Cellar/rbenv/1.1.2/libexec/rbenv exec ruby /Users/harun/Downloads/v1-Geometrie/Toolbox.rb'"
Traceback (most recent call last):
	2: from /Users/harun/Downloads/v1-Geometrie/Toolbox.rb:1:in `<main>'
	1: from /Users/harun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/harun/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- tk (LoadError)

Process finished with exit code 1

<img width="1904" alt="Screenshot 2020-01-27 at 16 44 09" src="https://user-images.githubusercontent.com/59563628/73189174-45914d80-4124-11ea-9c41-3abd149c0429.png">

**Comment by mislav** [comment]
Hi, thank you for reporting, but I think this issue is more with Ruby dependencies than the installation of Ruby. Ruby 2.7.0 does _not_ have bundled `tk` out of the box.

I don't know how Toolbox is supposed to work or what are its dependencies, but I think it might need to bundle tk itself: https://github.com/ruby/tk

If there are non-standard Ruby build options that you need to use in order to run Toolbox on it, then you need to recompile ruby:

```sh
RUBY_CONFIGURE_OPTS="..." rbenv install -f 2.7.0
```
