### ISSUE TITLE
rbenv is not allowing me to set a local ruby version, amongst other issues

### ISSUE THREAD

**Issue by brian-welch** [rbenv/rbenv#1213]
I have an existing web app and repo, and I am trying to set up a new local dev environment (since the computer I originally used to build the app has died) ☠️

I am having issues trying to install the right versions of Ruby and thereby Rails.

Asking some contacts, one suggested I need to make sure my paths are correct, though I am not sure how to do that.  I am running Z Shell(ZSH).

Can you steer me in the right direction?

Here are commands and responses for reference:
```
➜   ruby -v            
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
➜   rbenv -v           
rbenv 1.1.2
➜   rbenv versions
  system
* 2.4.4 (set by /Users/Brian_Welch/code/brian-welch/rails/['WEB-APP-NAME']/.ruby-version)
  2.5.3
```

Regards,

Brian

**Comment by mislav** [comment]
Hi @brian-welch, I'm sorry that you're having problems with rbenv.

rbenv works by prepending its shims directory to PATH. You can check `echo $PATH` to see if `~/.rbenv/shims` directory is at the start of your PATH. If not, then check your shell initialization file to see if it contains the `rbenv init` line as per installation instructions. You may need to restart your shell for the changes to take effect.

If you installed rbenv from git checkout, be sure to pull the latest changes, as we [just fixed a zsh bug](https://github.com/rbenv/rbenv/pull/1216) that was in effect since yesterday:
```sh
cd ~/.rbenv
git pull
```

**Comment by brian-welch** [comment]
Thanks so much for your assistance and especially thanks for rbenv
