### ISSUE TITLE
Trying to install rbenv but running into this problem: "Checking for rbenv shims in PATH: not found"

### ISSUE THREAD

**Issue by jaedashson** [rbenv/rbenv#1217]
I am a complete novice to Linux, so please forgive my ignorance.  I am running Ubuntu 18.04.3.

I am trying to install rbenv following these instructions: https://github.com/rbenv/rbenv#basic-github-checkout

First I tried to auto install with `wget -q https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer -O- | bash`.  I think it didn't work as expected because when the rbenv doctor script ran, it said my rbenv directory was in /home/[my name]/.rbenv but not in PATH.  I added it to PATH by running `echo 'export PATH="/home/[my name]/.rbenv/bin:$PATH"' >> ~/.bashrc`.  Now when I run the rbenv doctor script, I get this printout:

```
Checking for `rbenv' in PATH: /home/[my name]/.rbenv/bin/rbenv
Checking for rbenv shims in PATH: not found
  The directory `/home/[my name]/.rbenv/shims' must be present in PATH for rbenv to work.
  Please run `rbenv init' and follow the instructions.

Checking `rbenv install' support: /home/[my name]/.rbenv/plugins/ruby-build/bin/rbenv-install (ruby-build 20200115-8-g73b926b)
Counting installed Ruby versions: none
  There aren't any Ruby versions installed under `/home/[my name]/.rbenv/versions'.
  You can install Ruby versions like so: rbenv install 2.2.4
Checking RubyGems settings: OK
Auditing installed plugins: OK
```

Can someone tell me how I am supposed to proceed?  I tried running `export PATH="home/[my name]/.rbenv/bin:~/.rbenv/shims:$PATH"` but that didn't resolve the `Checking for rbenv shims in PATH: not found` issue.  I am sure I am missing something very basic, because I just trying to follow the instructions without really knowing what I am doing.  Thanks in advance.

**Comment by jaedashson** [comment]
I ran `source ~/.bash_profile` and then `echo 'eval "$(rbenv init -)"' >> ~/.bash_profile` and after that the rbenv doctor script printout matches that in the instructions, so I think this is resolved.

**Comment by Pauloparakleto** [comment]
@jaedashson It hept me! The official readme "think" everybody is proffesional.

**Comment by danielroblero** [comment]
Thank you @jaedashson - that worked for me!

**Comment by reygiovanni** [comment]
oh my God, thank you very much!

**Comment by erikaBell** [comment]
I'll reiterate reygiovanni: "oh my God, thank you ver much!"

**Comment by mchirino89** [comment]
I added these lines at the end of my .zsh file (for those of us who are using oh my zsh)

```bash
# rbenv configuration
eval "$(rbenv init -)"
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"
```

**Comment by vladpimonov** [comment]
@jaedashson thx man

**Comment by jgiordanoGG** [comment]
I was having the same issue, but using part of @mchirino89 's solution worked for me. All I had to do was add `eval "$(rbenv init -)"` to my `.zscrc` file and the rbenv doctor showed everything was ok.

**Comment by toppyc4** [comment]
@mchirino89 i try to run your line in my wsl but it's not understand brew command. How can I run it, Thanks

**Comment by mchirino89** [comment]
> @mchirino89 i try to run your line in my wsl but it's not understand brew command. How can I run it, Thanks

You need to have [`brew`](https://brew.sh/) installed in your system for it to work.

**Comment by glennposadas** [comment]
I added @mchirino89's stuff to my `.zshrc`, but it didn't work still, turned out I forgot to run `source ~/.zshrc`. Also, take heed of the error that the doctor (using the command below) says about your `.zshrc` file, e.g. missing `"` quote.

```
curl -fsSL https://github.com/rbenv/rbenv-installer/raw/main/bin/rbenv-doctor | bash
```

documentation: https://github.com/rbenv/rbenv#homebrew

**Comment by BlaneWins** [comment]
> I added these lines at the end of my `.zshrc` file (for those of us who are using _oh my zsh_)
> 
> # rbenv configuration
> eval "$(rbenv init -)"
> export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"

This was my issue in 2025 as well, can anyone explain why the "rbenv init" command in the readme doesn't work for oh-my-zsh? It seems to know it's Zsh and even creates the correct line in "/.zprofile" but how are we supposed to know to add the eval function??

**Comment by mislav** [comment]
Hi all, since this tread got bumped up, let's reiterate how to set up rbenv in 2025. Lots has changed since the start of this thread!

First of all, the user does not have to edit any shell files manually anymore. Running `rbenv init` will identify the current shell and [amend the appropriate shell initialization files](https://github.com/rbenv/rbenv/pull/1568) (such as `.zshrc` or `.bash_profile`) to add the `eval ...` line.

Second, setting RUBY_CONFIGURE_OPTS for openssl isn't necessary anymore. If openssl was installed via Homebrew, `rbenv install` (provided by the ruby-build project) will automatically pick that up.

Third, I don't know if users of oh-my-zsh need to do anything differently, but it seems like oh-my-zsh has an [rbenv plugin](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/rbenv/rbenv.plugin.zsh), so I would recommend just loading that plugin instead. But if there is a specific incompatibility with oh-my-zsh and our own installation instructions, please report that in a new issue and don't forget to include relevant portions of your `.zshrc` and `.zprofile`. Thank you!
