### ISSUE TITLE
rbenv not executing correct version of Ruby

### ISSUE THREAD

**Issue by LandonSchropp** [rbenv/rbenv#1224]
I'm trying to run `bundle exec guard`, and I keep getting this error:

```
Your Ruby version is 2.6.3, but your Gemfile specified 2.7.0
```

I have 2.7.0 installed locally via `rbenv`, and I have a `.ruby-version` file locally with 2.7.0 in it. If I do `ruby -v`, it prints out `ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]`.

I dug around in the `bundle` shim a little bit and noticed that it was running `rbenv exec`, so I tried running `rbenv exec bundle exec guard`, but it produces the same error.

If I do `which ruby && which bundle`, I get this:

```
/Users/landon/.rbenv/shims/ruby
/Users/landon/.rbenv/shims/bundle
```

I'd really appreciate any suggestions on this. This issue is blocking me. Thanks in advance!

**Comment by hsbt** [comment]
It’s the expected behavior of bundler. see https://bundler.io/gemfile_ruby.html

**Comment by hsbt** [comment]
Ah sorry, It seems an issue of rbenv.

**Comment by LandonSchropp** [comment]
No problem. Any ideas what's happening here? I'm happy to provide more information if needed.

**Comment by mislav** [comment]
Hi, I'm sorry you're having trouble. I have no idea what's happening, but Bundler sometimes does weird things with version switching/locking at runtime. The fact that running `ruby -v` prints the correct version suggests that rbenv is configured properly and does its job well, but something goes awry in `bundle` specifically. This smells like an issue on your end and not with rbenv, but I can't be sure.

Do you have any rbenv plugins installed?

BTW, you should not ever have to run `rbenv exec` specifically. As long as shims are correctly in your PATH, you should just run `bundle exec ...`.

**Comment by LandonSchropp** [comment]
Thanks for the reply! The only plugin I have installed is `ruby-build`.

I agree this seems fishy, but I'm not sure where to start in debugging this.

Is there any ways that my local path could be getting in the way? Is it possible that the Bundler command is executing a different version of Ruby? Could rbenv be executing Bundler with the wrong version?

Thanks for the help!

**Comment by LandonSchropp** [comment]
I'm happy to provide any more information you may think is relevant. Here's my path if it's helpful:

```
/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:./bin:./node_modules/.bin:/Users/landon/.rbenv/shims:/Users/landon/.rbenv/shims:/Users/landon/.dotfiles/bin/git:/Users/landon/.dotfiles/bin/docker:/Users/landon/.dotfiles/bin/gcloud:/Users/landon/.dotfiles/bin:/Users/landon/.dotfiles/bin/git:/Users/landon/.dotfiles/bin/docker:/Users/landon/.dotfiles/bin/gcloud:/Users/landon/.dotfiles/bin:/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:./bin:./node_modules/.bin:/Users/landon/.rbenv/shims:/Users/landon/.nvm/versions/node/v12.15.0/bin:/Users/landon/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/landon/.dotfiles/bin/git:/Users/landon/.dotfiles/bin/docker:/Users/landon/.dotfiles/bin/gcloud:/Users/landon/.dotfiles/bin
```

**Comment by jasonkarns** [comment]
I see you have `./bin` ahead of the rbenv shims in your PATH... Any chance the local directory binstub is taking priority? I seem to also recall some ruby binstubs being written that hard-code their shebang...

I also have an uneasy feeling that this may be related to the switch of bundler from being a gem to its being bundled within ruby itself. 😬

**Comment by mislav** [comment]
@jasonkarns I have that feeling too 😕 

@LandonSchropp Definitely check for `bin/bundle` and similar binstubs within your project since they might take precedence!

**Comment by LandonSchropp** [comment]
I checked my `bin` directory, but there's no binstubs for `bundle` or `ruby` in there. I double-checked the `which` command and they're there.

At this point, I may reformat my machine. My dotfiles are automated, so that may be a faster resolution.

**Comment by mislav** [comment]
> At this point, I may reformat my machine. My dotfiles are automated, so that may be a faster resolution.

That sounds like a nuclear option, and if it did fix it, nobody would be any wiser.

I would advise against nuking everything and patiently digging through binstubs and code until you can figure out what was going on and potentially learn from it.

For example, what if you run the appropriate `bundle` executable directly, i.e. skipping rbenv? 
```
`rbenv prefix`/bin/bundle
```

If that yields the same error, the error is in Ruby or Bundler. If everything works like a charm, then the bug is likely somewhere in rbenv interacting with Bundler

**Comment by Pauloparakleto** [comment]
Hi @LandonSchropp and @mislav, so did I,
Taking a little close to the beginning of the rbenv documentation (How rbenv works), I worked around uninstalling my global ruby version in order to avoid the compiler to find it. See mainly the order in which the compiler search ruby versions to take the best decision to your case.
As @mislav said, it is a strong possibility you have configured your rbenv properly.
Ps: As I don't know bundler priority path, I did what I did.

**Comment by rally25rs** [comment]
same issue on macOS Catalina

```
$ ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

$ rbenv version
system (set by /Users/jvalore/.rbenv/version)

$ rbenv install 2.5.3
...output omitted...
Installed ruby-2.5.3 to /Users/jvalore/.rbenv/versions/2.5.3

$ rbenv global 2.5.3

$ rbenv versions
  system
* 2.5.3 (set by /Users/jvalore/.rbenv/version)

$ which ruby
/Users/jvalore/.rbenv/shims/ruby

$ ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
```

**Comment by imAunAbbas** [comment]
I tried every solution, but nothing worked for me. I installed the Ruby `2.7.6` but was still not able to see the change even after running the command; `rbenv global 2.7.6`. It was still showing the default OS version when I checked it using `ruby -v`. I was placing the path in `.zshrc` file.

I'm using `MacBook Pro M2` with macOS `Ventura 13.2` and in my case, I placed the following code in the `.zprofile` file instead of `.zshrc`:

    export PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init - zsh)"

And it worked for me and I checked it by creating a project as well. I'm using `React Native 0.71.2`, which needed Ruby `2.7.6` version.
