### ISSUE TITLE
Looking for maintainer's opinion/best pracitce on ExecStart for systemd services

### ISSUE THREAD

**Issue by rromanchuk** [rbenv/rbenv#1225]
Hi @mislav I'm just looking for your opinion on how you personally would setup service files with `systemd` that needs to execute a command in the same context as an interactive login shell running `bundle exec`, in a properly configured environment. 

One thing that has been annoying me over the years is the myriad different ways i see people doing this.  You can see this struggle bus when searching [rbenv puma systemd](https://www.google.com/search?q=systemd+puma+rbenv&aqs=chrome..69i57j0.3903j0j1&sourceid=chrome&ie=UTF-8)

Below is truncated example for the most common puma, rails, capistrano-y deploy paradigm.  Some of the variations i see are 

Absolute path method 

`/home/ubuntu/.rbenv/shims/bundle exec`

Invoking -l, some setting up the environment PATH variable, others not

`/bin/bash -lc 'bundle exec`

Shouldn't we really just be using `bundle binstubs puma` on deploy then using an `ExecStart={{deploy_directory}}/bin/puma`? It seems to be the least smelly approach. I feel like I have tried that in the past but for whatever reason i'm not at the moment. I think i already have my answer as it's literally recommended here https://github.com/rbenv/rbenv/wiki/Deploying-with-rbenv#app-bundles-and-binstubs. I wonder if it all stems from a confluence of user errors, i could see someone deploying without appropriate path environment, unknowingly executing  with system ruby/bundler  and then correctly/incorrectly trying to run gems under rbenv.  

```
[Unit]
Description=Puma HTTP Server
After=network.target
Requires=puma.socket

[Service]
Type=simple
WorkingDirectory={{deploy_directory}}/current

# Looking for best practices for these two params
Environment=PATH={{appropriate_path_with_rbenv_shims}}
ExecStart= # best practice?

[Install]
WantedBy=multi-user.target
```

**Comment by mislav** [comment]
Hi! I have no experience with systemd or ExecStart, so I can't tell what the best advice for that is in general. I would still follow our wiki in its advice about binstubs, though. I feel like that is the most easy to set up and resilient approach.

Of course, other approaches could also be taken, such as ensuring that rbenv shims are in the PATH.

We can't really expand rbenv documentation with how to set up one's servers because everyone seems to have a bit different approach based on their architecture and there is no really one-size-fits-all approach for rbenv on the server. But if you come across a really solid and easy approach, I would love if you'd expanded our wiki page with notes about that.

Anything else before we can close this?

**Comment by rromanchuk** [comment]
@mislav that makes sense thanks. i think i can supplement wiki with some details where i think must people people are getting tripped up, especially where services and tools are attempting to execute ruby outside the user's traditional login shell

**Comment by scottmacpherson** [comment]
@rromanchuk, I'm curious how you setup `Environment` in your systemd services, as I believe rbenv still needs to be on PATH. Do you hardcode the value?

**Comment by rromanchuk** [comment]
@scottmacpherson i moved those paths up to the “global” *nix ‘printenv’ for all machines. I have a base image provision that essentially sets these Environment vars for rbenv, so I don’t have to deal with it in each .service (Sidekick, rake, etc)
