### ISSUE TITLE
this does not work

### ISSUE THREAD

**Issue by thefonso** [rbenv/rbenv#1228]
$ ~/.rbenv/bin/rbenv init

This is not working...when I run this I get the following output

```
# Load rbenv automatically by appending
# the following to ~/.bash_profile:

eval "$(rbenv init -)"
```
I then place this line at the end of my bash_profile...and NOTHING happens. I can not run rbenv.

**Comment by mislav** [comment]
Hi, sorry you're having troubles!

Is bash your default shell? Which operating system are you on? If there is an existing `~/.bashrc` file instead of `~/.bash_profile`, can you try pasting the line there instead?

Remember to restart your shell after making changes so that the configuration takes effect.

**Comment by thefonso** [comment]
Looks like things are ok now and I can run rbenv per your help from this ticket...

https://github.com/rbenv/ruby-build/issues/1353#issuecomment-600726091

THANK YOU @mislav
