### ISSUE TITLE
clean install of rbenv will not install any rubies

### ISSUE THREAD

**Issue by Jailyard90Grad** [rbenv/rbenv#1240]
On macOS Mojave 10.14.6...rbenv 1.1.2

I recently had a few issues which caused me to uninstall rbenv and all my installed Rubies. I reinstalled rbenv but now I cannot install any Rubies.

I reinstalled rbenv through Homebrew, as I had originally, and according to the results of the rbenv-doctor script everything seems to be setup properly: https://gist.github.com/Jailyard90Grad/ed25a4fbe2fa751a78f3fef13f969246

However, every time I run `rbenv install`, I get the command prompt again without any dialog and with no attempt at an installation. Running `rbenv install -l` brings up a list of available rubies and my bash_profile includes: 
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

This is the first time I've ever had a problem with rbenv and I'm stumped as to how to proceed. Any thoughts?

**Comment by Jailyard90Grad** [comment]
-- UPDATE --

I haven't been able to fix this but I found a workaround and I thought I'd share in case this helps anyone else.

Both rbenv and ruby-build are in their own directory in /usr/local/bin/ and the paths are seem to be fine. However, it looks like the connection between the two is not working.

The `rbenv install` command never worked properly, BUT I was finally able to download a Ruby by running `ruby-build 2.5.1 ~/.rbenv/versions/2.5.1'

So...I can get back to work but I have no idea why this happened on a clean installation of rbenv. Hopefully this helps someone later.

**Comment by mislav** [comment]
I'm sorry you were having trouble.

> However, every time I run `rbenv install`, I get the command prompt again without any dialog and with no attempt at an installation.

That's so weird. If you try this `RBENV_DEBUG=1 rbenv install 2.5.1`, is there some extra output just before the command aborts that would help you narrow down why this happens?

**Comment by Jailyard90Grad** [comment]
@mislav Thanks for the response. I was finally able to get it to work yesterday before I saw your reply so I didn't have a chance to try this. Sorry. 

When I removed my Rubies I had also removed the Bundler gem. After downloading and installing 2.5.1, I re-installed Bundler and the `rbenv install` command worked again. I was able to use `rbenv install` to successfully download additional Rubies.

This was clearly an issue with my understanding of how ruby-build is connected to rbenv, but I found nothing anywhere in the docs about Bundler being necessary to make this work. Maybe I was just lucky but if Bundler *is* necessary, maybe an update to the wiki would be helpful.

And BTW...thanks for your work on rbenv. It's a great tool.

**Comment by jasonkarns** [comment]
For clarity to anyone who stumbles on this, bundler is _not_ a requirement for rbenv or ruby-build.

And to help clarify how ruby-build integrates with rbenv, the subcommand extension mechanism is similar to git's.

rbenv supports subcommand "registration":
1. if the executable's name begins with `rbenv-`
2. AND the executable is either in `PATH` or `$(rbenv root)/plugins/*/bin`

For instance, if you have an executable `rbenv-foo` in your `PATH`, then that executable will be invoked by the command `rbenv foo`. ruby-build includes the `[rbenv-install](https://github.com/rbenv/ruby-build/blob/master/bin/rbenv-install) executable, which is how the two are integrated.

If you install rbenv via homebrew, the homebrew formula installs both rbenv and ruby-build and symlinks them into `PATH`. Therefore the command `rbenv install` finds ruby-build's `bin/rbenv-install` executable because the homebrew formula links it into `PATH`. (You can find the subcommand delegation logic [here](https://github.com/rbenv/rbenv/blob/c2cfbd1e8b990f207a30cf7e190949a333a4e468/libexec/rbenv#L94-L126))

Alternatively, if you install ruby-build as a plugin by git-cloning into rbenv root, then an invocation of `rbenv install` invokes `$(rbenv root)/plugins/ruby-build/bin/rbenv-install`. (You can find the plugin path lookup logic [here](https://github.com/rbenv/rbenv/blob/c2cfbd1e8b990f207a30cf7e190949a333a4e468/libexec/rbenv#L73-L77))

I can't speak to what the underlying problem was here, but hopefully understanding how the subcommand is delegated might aid in debugging future issues.

**Comment by mislav** [comment]
Thank you @jasonkarns for the clarification!

@Jailyard90Grad I'm glad it works for you now!
