### ISSUE TITLE
Matching system engine/version ignored

### ISSUE THREAD

**Issue by dunrix** [rbenv/rbenv#1249]
`rbenv` does not check if there is `RUBY_ENGINE-RUBY_VERSION` matching with system installed version (specified in `.ruby-version` and set in `RBENV_VERSION`) and fails to run.

For example, *system* ruby matches project's `.ruby-version` - both are *"ruby-2.7.1"* but `rbenv` fails with
>  rbenv: version `ruby-2.7.1' is not installed (set by RBENV_VERSION environment variable)

Is there a reason to not include system engine/version check and use it as a fallback ?

I can upload a working PR if interested.

**Comment by mislav** [comment]
> Is there a reason to not include system engine/version check and use it as a fallback ?

There is just a general principle: rbenv enforces strong delineation between all versions (including "system") and doesn't ever do any kind of fallback. Therefore, it doesn't matter if the system version matches the current project version— rbenv will still fail since `2.7.1` is not installed and managed via rbenv.

We won't change this since it would complicate the implementation and I don't believe it would be of much help.

**Comment by dunrix** [comment]
@mislav Ok, makes sense.
