### ISSUE TITLE
Feature Request: stable branch that only gets updated with releases

### ISSUE THREAD

**Issue by mohamedhafez** [rbenv/rbenv#1292]
since we update rbenv with a simple `git pull`, it would be great if there was a `stable` branch that only got updated when a new version of rbenv was released. Currently, there's a bunch of commits to master after the latest release, and while I'm sure its fine now, it would be nice to only update to stable releases so we don't get hit by any bugs that may happen during the development of the next release.

**Comment by mislav** [comment]
Hi, thanks for the request, but rbenv has a simple versioning policy: you can either use tagged versions, or you can use the latest master. There will be nothing in-between, since maintaining stable branches would be too much work for me. I'll try to make a more recent tagged release soon.

**Comment by jasonkarns** [comment]
This could be scripted (or even made into a git alias unique to your rbenv checkout) such that you can pull latest, but only to the latest tag:

```
git fetch && git describe --tags --abbrev=0 upstream/master | xargs git merge --ff-only
```

This allows your checkout to remain on the master branch; but updates only jump forward to the latest tag, thus ignoring any commits on master that haven't been tagged. And since HEAD remains `master`, you don't have to worry about the repo being stuck on a stale detached head, or on a tag that won't ever be updated.
