### ISSUE TITLE
rbenv init succeeds with non-zero exit status

### ISSUE THREAD

**Issue by erjoalgo** [rbenv/rbenv#1300]

**Comment by jasonkarns** [comment]
This is intentional to indicative that `rbenv init` was not invoked per its purpose. As indicated in the output of `rbenv init`, its proper invocation is `rbenv init -` and the output to be sourced/evaled.

The error exit code is a safety guard so that a user does not mistakenly add `rbenv init` to their shell rc file and believe it to be functional.

Can you elaborate on why you think this is incorrect?

**Comment by erjoalgo** [comment]
Thank you for the clarification. I mistakenly ran the command on the terminal and believed it to have worked as intended after being able to invoke the installed binaries.
