### ISSUE TITLE
which -a rails generates duplicate ouputs

### ISSUE THREAD

**Issue by glennposadas** [rbenv/rbenv#1305]
This is not a priority issue, but perhaps rather a question.

After solving this issue, and after I followed the solution: https://github.com/rbenv/rbenv/issues/1106

Nothing worked for me, so I ended up running sudo gem install rails. Everything's fine but when running which -a rails, I get duplicate outputs:

```
glenn@Glenns-MBP proj-api % which -a rails
/Users/glennposadas/.rbenv/shims/rails
/Users/glennposadas/.rbenv/shims/rails
/Users/glennposadas/.rbenv/shims/rails
/Users/glennposadas/.rbenv/shims/rails
/usr/bin/rails
```

Question is, how do I clean these duplicates up?

**Comment by hsbt** [comment]
Maybe, you evaluate the multiple rc file like zshrc, zshenv and zprofile.

**Comment by mislav** [comment]
@glennposadas This can happen if the shell initialization code that eval's `rbenv init` output runs multiple times during the same shell session. This typically happens when running nested shells, tmux, or have improper shell configuration. By itself, it's not a problem that should prevent you from using Rails on your machine.
