### ISSUE TITLE
Add `--depth 1` to git installation instructions

### ISSUE THREAD

**Issue by DannyBen** [rbenv/rbenv#1328]
Hi,

Is there a reason to avoid `--depth 1` when cloning the repo for rbenv and associated plugins (assuming I am a *user* of rbenv, not a *developer*)?

If not - I suggest changing the README at least here and in the `ruby-build` instructions, to accelerate the installation for users, and hopefully alleviate some of the pain involved in all these installation instructions (for non-brew users).

**Comment by jasonkarns** [comment]
Possibly. Shallow clones incur additional overhead when doing subsequent pulls. Indeed, homebrew itself has stopped doing shallow clones for its taps (at GitHub's direction) due to the additional overhead. In short, `--depth 1` is only recommended for ephemeral clones that _will not be updated_. Since the installation directions are primarily geared towards developer's local machines which would expect to receive continued updates, we may not want to not recommend its use. OTOH, any docs geared towards deployment or CI boxes could receive that treatment.

**Comment by DannyBen** [comment]
I understand. Didn't know that shallow clone has overhead when updating. If this is the case, then I would leave things as is. People using CI, or other cases where shallow clone makes sense, will know to do so on their own.
