### ISSUE TITLE
Debian install: Link rbenv to standalone ruby-install if it exists 

### ISSUE THREAD

**Issue by Ragnoroct** [rbenv/rbenv#1345]
**When installing through apt, allow rbenv install to use recommended ruby-build binary**

I installed rbenv through apt install. It also installed ruby-install through `Recommends` 

```
$ dpkg -s rbenv
Package: rbenv
Status: install ok installed
Priority: optional
Section: ruby
Installed-Size: 75
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Version: 1.1.1-1
Depends: ruby | ruby-interpreter
Recommends: ruby-build
Description: simple per-user Ruby version manager
 rbenv lets you easily switch between multiple versions of Ruby. It's
 simple, unobtrusive, and follows the UNIX tradition of single-purpose
 tools that do one thing well.
Original-Maintainer: Debian Ruby Extras Maintainers <pkg-ruby-extras-maintainers@lists.alioth.debian.org>
Homepage: https://github.com/sstephenson/rbenv
```

```
$ which ruby-build && ruby-build --version
/usr/bin/ruby-build
ruby-build 20170726
```

```
$ which rbenv && rbenv --version && rbenv install
/usr/bin/rbenv
rbenv 1.1.1
rbenv: no such command `install'
```

I'm not sure what happens with homebrew but I'm guessing it links ruby-build automatically?

For debian installs maybe make rbenv detect standalone ruby-builds or add something to your shell source files to point to it.

**Comment by Ragnoroct** [comment]
If there is a good solution the maintainers like I can make the change in a pull request.

**Comment by mislav** [comment]
Sorry, but:
- The packaged ruby-build is from 2017, which is 4 years old. You wouldn't be able to install any newer version of Ruby using that.
- If the ruby-build package does not include the `rbenv-install` binary, and it looks like it doesn't, then `rbenv install` cannot possibly work.

My recommendation would be to install ruby-build manually as rbenv plugin, since the apt package is out of date.
