### ISSUE TITLE
Ubuntu packages vs latest release

### ISSUE THREAD

**Issue by nCubed** [rbenv/rbenv#1347]
With Ubuntu 20.04, installing rbenv with the package manager installs v1.1.1:

```
$ sudo apt install rbenv
# setup environment for rbenv, etc...

$ rbenv --version
> rbenv 1.1.1
```

No updates are found when updating the package manager: `sudo apt update`

Coming from a Windows background, I'm new to the Linux world and am wondering why the Ubuntu package manager is not updated with the latest release from 2019, over two years ago: v1.1.2?

Or maybe installing directly from Git is now the preferred method?

Ubuntu Packages Reference:
https://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=rbenv&searchon=names

**Comment by mislav** [comment]
Hi, welcome to the Linux world and to this project! Thanks for writing in.

The way projects like this one are packaged for various Linux distributions (incl. Ubuntu) is weird. Because there are so many different distributions (dozens of popular ones, or hundreds overall) of which many use different package managers and can have very different acceptance criteria for new packages, usually authors of the project (me in this case) do _not_ package and distribute the software for these distributions. Instead, contributors (basically, volunteers) who personally use a Linux distribution are the ones who package the software that they need and propose that it gets added to the official repository for the distribution. The packaging and proposal process is often lengthy and political, and not all software even gets accepted. If a project author wanted to go through this process in several Linux distributions at the time, and also every time for updates, they would have no time left to actually work on the project.

As you're guessing, the Ubuntu package wasn't built nor maintained by me, otherwise it wouldn't have fallen out of date. We could conceivably publish a Debian (Ubuntu-compatible) package from this repository, but I do not think that there is a need. Since rbenv doesn't have compiled components that are required for runtime, you can simply install it from git and always keep riding the latest state of the main branch. In this project, there is an implicit promise that the latest state of the main branch is always stable. Otherwise, you can install from git tags.

Hope that answers your questions! I'm going to close this since there is nothing actionable from me here anymore.

**Comment by nCubed** [comment]
@mislav Thanks for the incredibly insightful reply.

FWIW: The install readme is a bit confusing with the package manager being listed as the first option, followed by the recommended Git method. Perhaps there could be some verbiage added to the readme that recommends going with the Git method, and even link to this issue under the package installer method.

Again, your thoughtful reply is much appreciated and helps someone like myself (Windows bg) better understand what's happening in this world of Linux. Cheers!

**Comment by mislav** [comment]
Hm you're absolutely right. I forgot that for Ubuntu users, the package manager method is suggested front and center, and there's no warning that you will get an outdated package. I will reopen this as a documentation task then!

**Comment by thoni56** [comment]
This would be really helpful for us that (somehat) rely on package managers to at least give us a reasonably recent version ;-)

**Comment by tommyjanna** [comment]
Hi,

I ran into this situation while I was installing rbenv on my Debian installation last night. I want to update the documentation to help other users.

Please provide any suggestions to help improve this note! Thanks :D

**Comment by mislav** [comment]
@tommyjanna Well, for now, the easiest thing would be to remove the `Debian, Ubuntu and their derivatives` section of the README entirely, or at least provide a big warning that this will install an outdated version of rbenv and that users should better refer to the `Basic GitHub Checkout` approach.

Thank you!

**Comment by mislav** [comment]
> or at least provide a big warning that this will install an outdated version of rbenv and that users should better refer to the `Basic GitHub Checkout` approach.

Ha, it looks like you have already done that in the meantime 🎉 Awesome!
