### ISSUE TITLE
GPL License Compliance Issue

### ISSUE THREAD

**Issue by ISCAS-Vulab** [rbenv/rbenv#1395]
The file shobj-conf in your project is released under the GPL-3.0-or-later license. According to the GPL-3.0 license, the overall project also needs to be released under GPL-3.0-or-later license. The problem is that your project is licensed under the MIT license.

**Comment by mislav** [comment]
Thanks for pointing that out. This is my fault because I didn't think of the implications of importing GPL-licensed source code when I made this change: https://github.com/rbenv/rbenv/commit/8facb3b3a790fd275a4e8d5f4de474bbd837c040

Would an acceptable solution be to remove shobj-conf from our project and cut a new release of rbenv?

**Comment by ISCAS-Vulab** [comment]
There are 2 possible solutions:
1. You can change the project's license to GPL (generally not recommended)
2. If the shobj-conf file is not that required, you can remove it from the project； If it is necessary, you need to re-implement the corresponding function according to your own needs to replace that file.
