### ISSUE TITLE
Wrong ruby version invoked to run ruby script from Rails controller

### ISSUE THREAD

**Issue by gregwillits** [rbenv/rbenv#1396]
Admittedly stabbing the dark trying to determine whether rbenv, passenger, or bundler is responsible (and therefor not configured correctly by me).

Rails is running as 2.7.4, but calling a ruby script in a controller is causing 2.7.0 to be invoked.

```
Error:
/home/rcm/.rbenv/versions/2.7.4/lib/ruby/2.7.0/bundler/definition.rb:495:in `validate_ruby!':
Your Ruby version is 2.7.0, but your Gemfile specified 2.7.4 (Bundler::RubyVersionMisMatch)
```
Environment:
Ubuntu 20 > Apache > Passenger > rbenv > Rails > Controller > ruby script invoked with backticks

I have a collection of ruby scripts which run as CLI commands to talk to hardware external to the host. These are shared by multiple applications written with different front ends. All work fine called directly, and work fine when called by a Rails controller in dev mode, and even rails server -e production mode.

Specifically when running under Apache > Passenger, I get the mismatch error.

rbenv global is set to 2.7.4
There are .ruby-version files at multiple levels.
Gemfile has `ruby '2.7.4'`
Apache conf has `PassengerRuby /home/rcm/.rbenv/versions/2.7.4/bin/ruby`

From inside the controller 
`ENV['PATH']` = `home/rcm/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/bin:/usr/local/sbin:... etc`
`which ruby` = `/usr/bin/ruby` <-- why not the shimmed version?

If I eliminate the ruby line from the Gemfile, this eliminates the Mismatch error since there's no match to enforce, and the script runs. As a workaround for now that's fine (2.7.0 vs 2.7.4 not a big deal in the immediate term), but I'd still like to know what's happening here.

Is there any way that rbenv's version shimming is involved in this?

Sorry for the length. Thanks for reading.

**Comment by mislav** [comment]
This sounds tricky. I'll try my best to offer some advice here, but in the end it will be up to you to untangle what's happening here.

> `which ruby` = `/usr/bin/ruby` <-- why not the shimmed version?

I can't tell since you haven't shown us the contents of your full PATH variable, or at least the relevant entries. The `which` utility is very simple: it prints the first executable found when searching in each of the directories listed in PATH. If you are confused at the output of `which ruby`, then please check your PATH; specifically whether the `/home/<user>/.rbenv/shims` directory has precedence over other Rubies installed on the system.

It sounds like your app is shelling out to a Ruby script that is not part of the same app, i.e. that it's not meant to use the same gem bundle. If so, you need to reset Bundler-related environment variables when shelling out, such as BUNDLE_GEMFILE. Bundler offers a Ruby method to do this for you: https://bundler.io/man/bundle-exec.1.html#Shelling-out

Finally, keep in mind that rbenv doesn't seamlessly support shelling out to a different Ruby version than the one that's currently activated by the app: https://github.com/rbenv/rbenv/issues/121. When shelling out to a different Ruby version, you may need to edit your PATH to take out the entry `/home/<user>/.rbenv/versions/<version>/bin` that was prepended to PATH by rbenv when launching your Ruby app in the first place.
