### ISSUE TITLE
Proposed alternative to `eval $(rbenv init -)` (faster shell startup)

### ISSUE THREAD

**Issue by rlue** [rbenv/rbenv#1409]
I've been using rbenv for years and I absolutely love it.

In recent months, I've also discovered spinoffs for various other language ecosystems, like [pyenv](https://github.com/pyenv/pyenv), [nodenv](https://github.com/nodenv/nodenv), and [goenv](https://github.com/syndbg/goenv). Even better!

### The Trouble: Slow shell startup

Then I added all the following lines to my `.bashrc`:

```bash
for util in rbenv pyenv nodenv goenv; do
  PATH="$HOME/.$util/bin:$PATH"
  eval "$($util init -)"
done
```

and discovered that my shell startup time grew to ~500ms (presumably what's most expensive is sourcing completion scripts and defining the `xxenv()` helper function for each utility). It might not seem like a lot, but it makes launching the terminal emulator (or opening new tmux panes) feel really sluggish.

### The Answer: Defer `rbenv init` until it's actually used

Now I do this:

```bash
for util in rbenv pyenv nodenv goenv; do
  # 1. Also add `shims` dir to PATH
  PATH="$HOME/.$util/bin:$HOME/.$util/shims:$PATH"

  # 2. Define an alias that undefines itself and runs `rbenv init` on-demand
  alias $util="unalias $util; eval \"\$(command $util init -)\"; $util"
done
```

and my shell startup is super snappy again! The first time I run rbenv (or any binary in the shims directory) in a given shell session, it takes an extra ~100ms to load—which is almost unnoticeable compared to the 500ms I had to wait any time I opened a new terminal window.

### The proposal

Is there any way that this approach (or something like it) might be officially adopted by rbenv? I don't think it would be very elegant to put this in the README (_i.e.,_ under the official installation instructions). But maybe the output of `rbenv init -` could be modified somehow to make it work like this under the hood?

What do you think?

**Comment by mislav** [comment]
That's a pretty cool solution; thanks for sharing!

What do you think is the shell support for the `unalias ... eval` solution that you've proposed? Does it work across shells like bash, zsh, tch, ksh, fish?

**Comment by mislav** [comment]
> 2\. when invoking any rbenv shim

Why would we want the custom alias to resolve in this case? Shims are separate from shell integrations

**Comment by rlue** [comment]
Maybe I am off base here; I will admit I don't fully understand rbenv internals. 

My thinking is, I'd like to lazy-load rbenv whenever I run _any_ ruby command it has a shim for, and not just rbenv itself. So, I cd into a project I'm working on and run `bundle`, but rbenv hasn't been initialized yet. The bundle shim then invokes rbenv, which invokes my funky alias, which then runs the init script and voilà.

Is that not how it works?

---

One downside I had not considered yesterday is that the completion script doesn't load until rbenv or one of its shims has been executed. :\\

**Comment by mislav** [comment]
> The bundle shim then invokes rbenv, which invokes my funky alias, which then runs the init script and voilà.
> 
> Is that not how it works?

Close, but the shim does not have the ability to invoke your shell alias. The shim runs in a subprocess of your shell, which does invoke `rbenv`, but does _not_ trigger your shell aliases because the subprocess is a separate instance of bash. Additionally, shims require no rbenv shell integrations to work—they just want to be present in PATH.

Let's take a few steps back and go over how rbenv shell integrations work. First of all, it's absolutely possible to use most rbenv functionality _without_ ever enabling its shell integration. This is all that's needed:
```
export PATH=~/.rbenv/bin:~/.rbenv/shims:"$PATH"
```
Calling most rbenv commands, switching between versions, and executing shims will all work with this approach. Rbenv was intentionally designed to not need shell integrations (unlike RVM).

However, rbenv offers some integrations, and they are enabled by doing `eval "$(rbenv init ...)"` in your shell. What that does is:
- Ensures that shims are in PATH (although, you can also do this manually)
- Sets up rbenv completions
- Sets up the `rbenv` shell function - this enables commands that need to change the state of your running shell, and the only command that needs this is `rbenv shell`
- Automatically performs a `rbenv rehash` to ensure all shims are up to date (potentially slow—you can disable this by using `rbenv init - --no-rehash`)

So if you do have rbenv shell integrations enabled and you call `rbenv` in your shell, the first thing that executes is the `rbenv` function. You could theoretically make this lazy-loading by defining a `rbenv` alias. But, when shims execute `rbenv`, they are executing `~/.rbenv/bin/rbenv` and they will always skip any "rbenv" functions or aliases that you might have. That's why shims are unaffected by shell trickery.

> One downside I had not considered yesterday is that the completion script doesn't load until rbenv or one of its shims has been executed.

That's true :( It might be a dealbreaker. Some shells like zsh lazy-load completions, and I know that there are hacks for bash to lazy-load completions too, but I wonder whether all this is starting to be more trouble than it's worth.

**Comment by rlue** [comment]
Wow, was not expecting such a comprehensive treatment. 🙇🙇🙇 Learned a lot from you, big thanks!

(As a point of clarification, this whole misunderstanding appears to stem from me somehow getting all mixed up about my trial-and-error in the shell—I could have sworn that when I came up with my little hack two days ago, running shims would cause `rbenv` to get redefined as its shell helper function... but now that I try it again, that's clearly not the case.)

> I wonder whether all this is starting to be more trouble than it's worth.

100%. Getting lost down yak-shavey rabbit holes is definitely a trademark weakness of mine. Many, many thanks for your patience with me, and letting me lead you down the garden path! 😅
