### ISSUE TITLE
Install instructions not clear on how to activate newly installed Ruby version

### ISSUE THREAD

**Issue by fulldecent** [rbenv/rbenv#1424]
I completed the install instructions in the readme and it did not produce the expected result

<img width="1234" alt="Screen Shot 2022-09-06 at 15 50 43" src="https://user-images.githubusercontent.com/382183/188726021-de1232dd-6e5f-4002-8e2f-a71d1ce10b36.png">

Additionally this required me to run a `curl | bash` shell code which is not best practice.

**Comment by fulldecent** [comment]
Followed instructions

<img width="1499" alt="Screen Shot 2022-09-06 at 15 52 26" src="https://user-images.githubusercontent.com/382183/188726229-d5fce476-d1ee-455f-b049-319b072de48f.png">

**Comment by hsbt** [comment]
You could install `3.1.2` correctly.

**Comment by fulldecent** [comment]
You are correct, but not helpful.

People are using rbenv because they want to set up and use Ruby, not because they want to learn about version management of rbenv.

The default install instructions of Ruby says to [install Ruby](https://www.ruby-lang.org/en/downloads/), click here, and then they are directed to the rbenv instructions I have referenced above.

So the install instructions for rbenv would be more helpful and live up to the esteem that Ruby-Lang.org places on it by ending with a usable Ruby installation. As my issue above shows, this is not currently the case.

**Comment by mislav** [comment]
@fulldecent Thank you for raising this issue. I will reopen this because it's a common pitfall with new rbenv users that their system Ruby version will still be selected as default even after they've just installed a Ruby version. Our users often do not understand that they need to use `rbenv global <VERSION>` or `rbenv local <VERSION>` to actually activate the Ruby version they've just installed.

Another common installation pitfall is clearing the `rbenv init` step so that rbenv is properly loaded in the shell (if needed) and that rbenv shims directory is added to PATH https://github.com/rbenv/rbenv/issues/1193

I think rbenv should do more to help users around these issues and hopefully reduce frustration.

**Comment by fulldecent** [comment]
Thank you, `rbenv global ...` worked for me. Here's a few ideas:

1. `rbenv install` can include a banner (in color) if rbenv is not currently enabled (explain to use `rbenv global/local`)
1. `rbenv-doctor` can say no shims if there are no shims in the path (failed as per screenshot above)
1. `rbenv-doctor` can more clearly say "Your RBENV is not active... (red/fail)" or clearer language that action is required
1. `rbenv-doctor` should be built into `rbenv`, it should not require a separate shell code hack which turns control of my entire computer over to anybody that controls github.com, the bin/rbenv-doctor file, anybody that can forge certificates on behalf of the trusted CAs in my toolchain, or anyone that can successfully perform a QUANTUMINSERT attack
2. `rbenv init` should perform its own checking and inform that an install / global / local needs to be performed
1. `rbenv init` should ask you to install a ruby version, with the latest stable version preselected (if one is not already installed)
2. `rbenv install` should default to the `-l` option with "The following versions are available. Use rbenv install VERSION to install a specific version."

**Comment by saeid-elio** [comment]
I just installed rbenv to use an old Ruby version (2.6.10), but my mac is still using my newer Homebrew version of Ruby that I had before (4.5.10). Why is that? 

````
sm@Mac app-now % rbenv version
2.6.10 (set by /Users/sm/apps/app-now/.ruby-version)
sm@Mac app-now % brew -v
Homebrew 4.5.10
````

**Comment by mislav** [comment]
> Could it be because I have these lines in my .zshrc?
> 
> ```
> export PATH=/opt/homebrew/bin:$PATH
> export PATH=/opt/homebrew/opt/ruby/bin:$PATH
> ```

It's probably because of that. If you do `which -a ruby` in your shell, it will show you an ordered list of what is found in PATH when you would run a `ruby` command. It's likely that `/opt/homebrew/opt/ruby/bin/ruby` is the first result.

If you want rbenv to perform version switching, then rbenv's shim directory needs to be higher up in PATH. That means you'll want to do rbenv setup as the last thing in your zshrc:

```sh
export PATH=/opt/homebrew/opt/ruby/bin:$PATH
...
eval "$(rbenv init - zsh --no-rehash)"
```
