### ISSUE TITLE
Consider changing Gem.user_dir or at least add a way to disable user bin support

### ISSUE THREAD

**Issue by konsolebox** [rbenv/rbenv#1442]
PR #1436 adds limited support for user-installed gems by including their executables in `rbenv`'s `rehash` and `which` targets.  This unfortunately allows another ruby (which may be `system` or another version with the same major and minor versions) that's different from the one currently configured with `rbenv local/global` to be called if that other ruby version installs the same gem, because it will override the bin executable with a new `#!` header that targets itself.  This allows user to unexpectedly call a different version of the gem, different dependencies, native gems that may run differently depending on build-time configurations or header values, or simply a version of Ruby with different RbConfig values.

It's just intuitively not right to allow gems to be shared among different ruby installs.  It theoretically allows different runtime results to happen, and it won't be easy to detect always.

Instead of statically detecting user's bin directory which can also be in `~/.local` instead of `~/.gem`, it would be better to just move the user directory instead.  This way the location of the executables becomes apparent and it will be possible to provide complete support to gems installed using `--user-install`.

I shared a [code in the PR #1436](https://github.com/rbenv/rbenv/pull/1436#issuecomment-1264238738) which allows this.  In that code the user directory simply becomes the main gem directory itself but separating them is fine too if future support for shared `rbenv` installs are considered and using a single directory might be a problem for it.

If for some fairly pragmatic reasons this gets rejected, please at least allow a way to disable the inclusion of user bins so I can use my configurations cleanly.  I just don't want to worry about the executables causing problems even a tiny bit regardless of how often the problems can happen.

Side info: In Gentoo the issue is actually partially avoided because user binaries are installed to `~/bin` (see Gentoo's [current defaults](https://github.com/gentoo/gentoo/blob/3eb0cfe339e79270446731b8f27bdc1b060d023b/dev-ruby/rubygems/files/gentoo-defaults-5.rb#L15) and a related [PR](https://github.com/gentoo/gentoo/pull/24611) where it was discussed), and it allows user `PATH` to only include `~/bin` ignoring `~/.gem/ruby/<version>/bin`, and makes `rbenv` not find the ones in `~/bin`.  But here gems can still be shared among different rubies installed with `rbenv` with same major and minor versions and `rbenv` should always be considerate of vanilla configurations.

**Comment by mislav** [comment]
Hi, thanks for the warning.

> If for some fairly pragmatic reasons this gets rejected, please at least allow a way to disable the inclusion of user bins so I can use my configurations cleanly.

I'm in the process of adding a `RBENV_USER_GEMS=off` setting that will disable user gems lookup completely. How does that sound?

> Instead of statically detecting user's bin directory which can also be in `~/.local` instead of `~/.gem`

Ah, thanks for this. I didn't know Rubygems supported XDG_DATA_HOME, but now I see that it does (in the case `~/.gem` does not already exist on disk).

> it would be better to just move the user directory instead. This way the location of the executables becomes apparent and it will be possible to provide complete support to gems installed using `--user-install`.

This is a good proposal. I will think about this. Thank you!

**Comment by mislav** [comment]
> It's just intuitively not right to allow gems to be shared among different ruby installs. It theoretically allows different runtime results to happen, and it won't be easy to detect always.

Agreed, but Ruby decided to have user gems support and to share e.g. Ruby 2.7 gems across all 2.7.x installs, and since Ruby supports that I thought it was only fair that rbenv supports it as well.

User gems support should not inadvertently affect anyone who doesn't use them.

Also note that running e.g. `bundle` will never activate `~/.gem/ruby/3.1.0/bin/bundle` if `$RBENV_ROOT/versions/3.1.2/bin/bundle` exists.

**Comment by konsolebox** [comment]
> I'm in the process of adding a `RBENV_USER_GEMS=off` setting that will disable user gems lookup completely. How does that sound?

I'll prefer something more specific like `RBENV_NO_USER_BIN_LOOKUP` where having it set to any value disables the lookup. `RBENV_USER_GEMS=off` seems to imply that user directories i.e. `Gem.user_dir` are disabled (at least virtually) by having it set to same directory as the nonuser directory like what I did.  I'm ok with anything though.

**Comment by konsolebox** [comment]
> > It's just intuitively not right to allow gems to be shared among different ruby installs. It theoretically allows different runtime results to happen, and it won't be easy to detect always.
> 
> Agreed, but Ruby decided to have user gems support and to share e.g. Ruby 2.7 gems across all 2.7.x installs, and since Ruby supports that I thought it was only fair that rbenv supports it as well.

My take on this is that they probably didn't think that a system will sensibly have two same x.y versions at the same time. Gentoo for example only allows x.y package slots.

This however becomes different when a user-oriented ruby manager is installed, or if a manager allows multiple patch versions of same x.y.

> User gems support should not inadvertently affect anyone who doesn't use them.

Sorry can you elaborate how? Bin stubs by default point to their specific `ruby`s.

> Also note that running e.g. `bundle` will never activate `~/.gem/ruby/3.1.0/bin/bundle` if `$RBENV_ROOT/versions/3.1.2/bin/bundle` exists.

Because `rbenv-which` avoids them yes? I guess that strategy is not a bad thing since the stub will automatically call the right gem, although it only works if the default bin executable exists.

**Comment by mislav** [comment]
> > User gems support should not inadvertently affect anyone who doesn't use them.
> 
> Sorry can you elaborate how? Bin stubs by default point to their specific `ruby`s.

True. What I meant was that, if you haven't been using `gem install --user-install`, this new rbenv feature should not negatively affect you. And if you have been using `gem install --user-install`, then you should be aware that there might be some fuzziness around which Ruby version will be activated when you invoke their binstubs. I agree that this might be odd since rbenv historically never allowed any “fuziness” and strictly kept all Ruby versions separate.

Those users like you who need very strict separation of Ruby versions should avoid ever using user-installed gems. Or, of course, to set the RBENV_NO_USER_BIN_LOOKUP to make user-installed gems essentially invisible to rbenv.

Does this sound acceptable? I'd welcome any advice on how to make the feature of supporting user-installed gems more resilient. Historically, rbenv chose to not support this, but then our users kept reporting that as a bug, so I thought it would be a nice touch for future rbenv to support this.

> Because `rbenv-which` avoids them yes?

Yeah, `rbenv-which` will first look up the executable within the Ruby version's main bin directory, and only if missing it will also look up user gems. That way, the way rbenv worked before is always the default mode, to keep maximum backwards compatibility.

**Comment by konsolebox** [comment]
> Those users like you who need very strict separation of Ruby versions should avoid ever using user-installed gems. Or, of course, to set the RBENV_NO_USER_BIN_LOOKUP to make user-installed gems essentially invisible to rbenv.
> 
> Does this sound acceptable?

With the variable yes, I can be content with it.

**Comment by mislav** [comment]
@konsolebox Thank you for all the feedback. After some deliberation, I have entirely removed support for discovering and dispatching to executables found in `~/.gem/<engine>/<version>/bin` directories. I could not find a way to do it in a way that would work with all Ruby versions and not slow down rbenv considerably.

Support for explicitly set GEM_HOME environment variable still stays. 👍
