### ISSUE TITLE
RBENV_VERSION_ORIGIN doesn't make sense 

### ISSUE THREAD

**Issue by konsolebox** [rbenv/rbenv#1451]
In `rbenv-version-origin`, `RBENV_VERSION_ORIGIN` is checked if it has values after hooks to `version-origin` has been executed.  This implies `RBENV_VERSION_ORIGIN` can only be set by the hook scripts.

```
unset RBENV_VERSION_ORIGIN

OLDIFS="$IFS"
IFS=$'\n' scripts=(`rbenv-hooks version-origin`)
IFS="$OLDIFS"
for script in "${scripts[@]}"; do
  source "$script"
done

if [ -n "$RBENV_VERSION_ORIGIN" ]; then
  echo "$RBENV_VERSION_ORIGIN"
elif [ -n "$RBENV_VERSION" ]; then
  echo "RBENV_VERSION environment variable"
```

However, in `rbenv-which`, hook scripts are executed after `RBENV_VERSION` has been used to check executables.  This doesn't make sense because aren't scripts also supposed to be the one to alternatively set `RBENV_VERSION` in that script too?

```
RBENV_VERSION="${RBENV_VERSION:-$(rbenv-version-name)}"

if [ "$RBENV_VERSION" = "system" ]; then
  PATH="$(remove_from_path "${RBENV_ROOT}/shims")" \
    RBENV_COMMAND_PATH="$(command -v "$RBENV_COMMAND" || true)"
else
  RBENV_COMMAND_PATH="${RBENV_ROOT}/versions/${RBENV_VERSION}/bin/${RBENV_COMMAND}"
fi

if [[ ! -x "$RBENV_COMMAND_PATH" && -n "$GEM_HOME" && -x "${GEM_HOME}/bin/${RBENV_COMMAND}" ]]; then
  RBENV_COMMAND_PATH="${GEM_HOME}/bin/${RBENV_COMMAND}"
fi

OLDIFS="$IFS"
IFS=$'\n' scripts=(`rbenv-hooks which`)
IFS="$OLDIFS"
for script in "${scripts[@]}"; do
  source "$script"
done
```
What exactly is the purpose of `RBENV_VERSION_ORIGIN` or when should a value be assigned to it?

If hook scripts are meant to assign values through the `version-name` hook instead, wouldn't that be inconsistent if `RBENV_VERSION` has already been assigned through the environment?  `rbenv-version-name` itself would be skipped and the origin should be `"RBENV_VERSION environment variable"` but it would be `${RBENV_VERSION_ORIGIN}`.

**Comment by mislav** [comment]
Hi, thanks for the good question.

In short:
- `version-name` hook: allows overriding the rbenv version that will be used when dispatching a command. One can use that, for example, to read the Ruby version from `Gemfile` instead from a `.ruby-version` file.
- `version-origin` hook: set a human-readable label that explains how the version was determined.

rbenv shims are executed first via `rbenv exec`, which allows modifying RBENV_VERSION: https://github.com/rbenv/rbenv/blob/6b1cc34610c53d846f3ec35bcdd1cf6000c4a320/libexec/rbenv-exec#L24

Therefore, if a plugin wanted to modify the version and override even the `RBENV_VERSION` value inherited from the environment, it could.

You are right that `rbenv which` would skip any `version-name` hook if the environment variable is set: https://github.com/rbenv/rbenv/blob/6b1cc34610c53d846f3ec35bcdd1cf6000c4a320/libexec/rbenv-which#L37

This is a speed optimization, since the environment variable is expected to be prepared by `rbenv exec`.

> What exactly is the purpose of `RBENV_VERSION_ORIGIN` or when should a value be assigned to it?

A value should be assigned to RBENV_VERSION_ORIGIN if there was also a `version-name` hook that does some special steps to determine RBENV_VERSION. If RBENV_VERSION was already set from the environment, though, both `version-name` and `version-origin` hooks should likely not do anything. They can if they want to, but it would be an overreach on their part.

Does this make sense?

**Comment by konsolebox** [comment]
Yes I'm contented with the answer, thanks.

**Comment by mislav** [comment]
I've added a bit of documentation to https://github.com/rbenv/rbenv/wiki/Authoring-plugins#rbenv-hooks
