### ISSUE TITLE
Cant update ruby version to 2.7.6 from 2.6.10

### ISSUE THREAD

**Issue by Sargnec** [rbenv/rbenv#1480]
![Screenshot 2023-02-09 at 16 08 38](https://user-images.githubusercontent.com/49839699/217822930-1897aa77-4a19-4045-8ff7-fef381074fc5.png)
I try to install 2.7.6 version but my ruby -version stays at 2.6.10p210

**Comment by mislav** [comment]
Hi, you've selected a global version `2.7.6` correctly, but you have also selected a "local" version `2.7.6` for everything under your home folder `/Users/necmettinsargin`. The "local" version takes precedence over "global", so I would suggest first fixing that:
```
cd ~
rbenv local --unset
```
Then, since `ruby --version` still reports version `2.6.10`, which is the system Ruby version on macOS, I would guess that you have not finalized setting up rbenv per our installation instructions. If you run `echo $PATH`, you can see a list of paths that are looked up in order whenever you run `ruby`, and the first `ruby` found in PATH is going to get executed. If you finished setting up rbenv, then `/Users/necmettinsargin/.rbenv/shims` will be one of the first entries in your PATH, but if that is not the case, then revisit our installation instructions, particularly around `rbenv init`. Running `rbenv init` and following the instructions that it prints out for you might be enough to get everything working.

Good luck!

**Comment by Sargnec** [comment]
Thanks @mislav. Had to make some research to add _eval "$(rbenv init - zsh)"_  to zshrc but finally did it
