### ISSUE TITLE
Ubuntu 22 - no ruby 3.1.2

### ISSUE THREAD

**Issue by alterisian** [rbenv/rbenv#1502]
Hi, 
Just upgraded to Ubuntu 22, after using 20, with rbenv.
I have apt-get removed rbenv, and apt-get installed rbenv, just incase
 
rbenv --version
rbenv 1.1.2
ruby-build --version
ruby-build 20200401

Before/after I get a fairly long list of rubies, but no 3.x.x's.

Get an error message to try to update ruby-build when trying to install 3.1.2
```
benv install 3.1.2
ruby-build: definition not found: 3.1.2
See all available versions with `rbenv install --list'.
If the version you need is missing, try upgrading ruby-build.
```

Looking into this gives a path for ruby-build that does not exist on Ubuntu:
https://github.com/rbenv/ruby-build#install-manually-as-a-standalone-program

However, which gives:
which ruby-build
/bin/ruby-build

But changing the prefix to this does not work:
sudo PREFIX=/bin ./ruby-build-*/install.sh
(or give an error. But the ruby-build --version is still the same)

Time to sleep on it, and see if anyone has ideas tomorow.

**Comment by mislav** [comment]
Hi, your ruby-build version from Ubuntu repositories is more than 3 years old and does not include any Ruby versions that were released since then. We do not maintain the ruby-build package in Ubuntu repositories; someone else does that, and they have not been updating.

You should follow the instructions for installing ruby-build as rbenv plugin using git. This will guarantee you the latest version of ruby-build. Meanwhile, you can uninstall ruby-build that you've installed using apt.

**Comment by alterisian** [comment]
Ok, will document here incase there are others facing the issue. And update the twitter thread too.
