### ISSUE TITLE
Question: why rbenv recommends inserting initial command to `~/.zshrc` instead of `~/.zshenv` or `~/.zprofile` ?

### ISSUE THREAD

**Issue by ono-max** [rbenv/rbenv#1508]
.zshrc is only loaded when zshell is executed as an interactive mode. Could you tell us the reason that rbenv recommends inserting initial command to `~/.zshrc` instead of `~/.zshenv` or `~/.zprofile`?

## Background

I'm a member of [VS Code Extension for Ruby debugger](https://github.com/ruby/vscode-rdbg). Currently, we have a problem of https://github.com/ruby/vscode-rdbg/issues/277#issuecomment-1584441941. And the problem occurs by using an interactive mode in zshell. We execute commands like follows in the interactive mode to load .zshrc.

```sh
/bin/zsh -lic "rdbg --util=list-socks"
```

Thank you!

**Comment by mislav** [comment]
Sorry that this cost so much time to track down for people using Ruby debugger from VS Code.

The primary reason why we suggest putting rbenv initialization in `zshrc` is because we only wanted rbenv shell integrations to be loaded in interactive mode and not in non-interactive mode.

This is what `eval "$(~/.rbenv/bin/rbenv init - zsh)"` does in one's shell:
1. Adds `rbenv` to PATH (if not already on PATH);
2. Prepends rbenv's `shims` directory to PATH - this is crucial for ruby version switching;
3. Loads rbenv shell completions;
4. Executes `rbenv rehash`;
5. Loads rbenv shell integrations (e.g. making `rbenv shell` command possible).

Only item (2) is actually necessary for ruby version switching; everything else is just convenience primarily made for interactive shells.

In summary, if someone wanted to ensure that their ruby version switching stays active in a non-interactive zsh shell, they should add this to their `~/.zshenv` (assuming the default RBENV_ROOT setting):
```
export PATH="$HOME/.rbenv/shims:${PATH}"
```
But to aid interactive shells, they should still be adding the `eval…` line to their `zshrc` file. You can imagine that making a full setup like this is hard to document and explain in our setup guide. We went the easy path, leaving most of the fine-tuning as the responsibility of the user. Unfortunately, I suspect that most users aren't aware of shell nuances like this, and I wish we could do this better. But to improve the situation, we would have to move from manual setup (i.e. having users follow installation instructions) and onto a more automated setup (i.e. an installation script editing files like zshenv and zshrc for you).

Do others have a strong opinion on how rbenv could improve in this regard?
