### ISSUE TITLE
`rbenv init` fails in parallel environment

### ISSUE THREAD

**Issue by lhunath** [rbenv/rbenv#1518]
`rbenv rehash` was written such as to obtain an exclusive lock using a shim AND to completely fail the entire process if that lock cannot be obtained.

This results in `rbenv init` being unreliable in any parallelized environment, such as when a build performs multiple independent build operations within the same rbenv that each need to initialize their shell.

There is no reason why `rbenv rehash` should hog the entire rbenv using a locked shim just to rehash the current shell environment. The current shell and the rbenv are independent entities and it should be perfectly valid to use the rbenv from multiple concurrent shell or execution contexts.

This is a very tricky thing to track down since `rbenv-rehash` was written to silence and obscure the error, making `rbenv init` fail without any error indication, leaving the user utterly confused as to why their build fails randomly. Tracking this down was a chore.

You can reproduce the issue easily using something like this:
```
for i in {0..100}; do ( rbenv rehash &>/dev/null; echo $? ) & done
```
You'll notice some `rbenv rehash`s succeeding and most failing.

Options:
1. `rbenv rehash` should NOT lock the rbenv environment using some kind of shim and it should operate exclusively within the current shell environment.
2. If `rbenv rehash` really needs to lock the entire rbenv environment, then it needs handle the situation where a lock exists without tearing down its calling environment. Probably it should wait to acquire the lock.

**Comment by mislav** [comment]
Hi, thanks for the detailed report.

It's a known problem that `rehash` fails in parallel. Since rehash is done on the filesystem, and there is only a single location at a time for rbenv shims on the filesystem, multiple `rehash` operations in parallel cannot be implemented feasibly, at least not in bash.

It's for this reason that eval'ing `rbenv init` performs `rbenv rehash 2>/dev/null`, effectively silencing its error output. We choose to ignore the error for the exact case that you are describing: multiple `rbenv init`s running in parallel is a viable use-case for which `rehash` isn't a step that should fail the whole operation.

However, it sounds like you are saying that `rbenv init` would halt at the failed `rehash` step. Do you have `set -x` enabled in your interactive shell by any chance, i.e. halting script execution at any failed command?

**Comment by mislav** [comment]
> However, it sounds like you are saying that `rbenv init` would halt at the failed `rehash` step. Do you have `set -x` enabled in your interactive shell by any chance, i.e. halting script execution at any failed command?

Closing due to lack of info.
