### ISSUE TITLE
Permission issues on MacOS besides set the ruby version with rbenv

### ISSUE THREAD

**Issue by ecureuill** [rbenv/rbenv#1563]
Hi! 
I've just installed ruby `2.7.0` version with rbenv and set it to global/local. But whenever I try to run `gem install bundler` I got directory permission error

```bash
% rbenv versions    
  system
  2.6.6
* 2.7.0 (set by /Users/suprisullocacaoeservicoltda/Documents/RD/.ruby-version)
```

And the error

```bash
% gem install bundler
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.
```

**Comment by billy-le** [comment]
I'm having the same issues.

I followed the install instructions. Mad sure rbenv was in my path. I checked if it was set using `rbenv global`, etc.

These were the steps I took:
`rbenv install 3.3.0` -> `rbenv global 3.3.0` -> `gem install bundler`

```
gem install bundler
Successfully installed bundler-2.5.9
Parsing documentation for bundler-2.5.9
Done installing documentation for bundler after 0 seconds
1 gem installed
```

I then ran `gem install cocoapods` and got the permissions error.
```
gem install cocoapods
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Users/billyle/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/CHANGELOG.md directory.
        /Users/billyle/.rbenv/versions/3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/installer.rb:356:in `rescue in install'
```

**Comment by mislav** [comment]
> ```shell
> % gem install bundler
> ERROR:  While executing gem ... (Gem::FilePermissionError)
>     You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.
> ```

This error message means that even though `rbenv version` shows the version 2.7.0 being selected, running `gem` still activates the system gem executable likely at `/usr/bin/gem`. Please ensure that you've set up rbenv correctly and that `which gem` shows `~/.rbenv/shims/gem` instead of `/usr/bin/gem`. This is done by either sourcing `rbenv init` into your shell or, if you don't want to do that, manually prepending `$HOME/.rbenv/shims` to your PATH.

> ```
> gem install cocoapods
> ERROR:  While executing gem ... (Gem::FilePermissionError)
>     You don't have write permissions for the /Users/billyle/.rbenv/versions/3.3.0/lib/ruby/gems/... directory.
> ```

This means that you might have used `sudo gem install ...` in the past, causing the `root` user to own some files under `~/.rbenv/verisons/3.3.0` instead of the `billyle` user. To reset ownership permissions back to your regular user account, run:

```
sudo chown -R $USER:staff ~/.rbenv/versions/3.3.0
```

**Comment by billy-le** [comment]
Thanks @mislav! I forgot what I did but I was able to install cocoapods. I'll definitely keep that in mind next time I run into trouble.
