### ISSUE TITLE
macOS installation - last step needs clarification

### ISSUE THREAD

**Issue by murfel** [rbenv/rbenv#1572]
I followed the [steps to install](https://github.com/rbenv/rbenv#installation) with Homebrew on macOS, and received this message at the end,

```
# Load rbenv automatically by appending
# the following to ~/.zshrc:

eval "$(rbenv init - zsh)"
```

Context:
```
% brew install rbenv ruby-build. # step 1
... # installation succesful
% rbenv init  # step 2

# Load rbenv automatically by appending
# the following to ~/.zshrc:

eval "$(rbenv init - zsh)"
```

The instruction also provides step 3, "reload terminal for changes to take effect". I did that and I'm 95% sure that didn't help and I did need to modify my ~/.zshrc. (I did some mingling in the terminal and cannot remember the correct sequence to success.)

It would be beneficial to either add an explicit step to ignore this zshrc message, or to mention to follow it with / instead of reloading the terminal / doing `source ~/.zshrc`.

Thank you! :)

**Comment by jasonkarns** [comment]
There is probably some room for clarification here. The instructions in step 3 "reload terminal for changes to take effect" is necessary _after_ any changes are made to ones zshrc. (The addition of rbenv-init to the zshrc are in fact the changes that will not take effect until reloaded.) Changes to zshrc/profile only take effect when they are sourced, which only happens when the shell is first launched.

So the instructions to add rbenv-init to your zshrc and the instructions to reload the terminal are not conflicting or redundant. Rather, the latter follows from the former.

I can see the confusion, however. The phrasing "Load rbenv automatically" could seem to imply the reload not being necessary.

**Comment by jasonkarns** [comment]
I think it's also likely you might be running into some conflicting messaging. Just a few weeks ago, rbenv-init [was modified](https://github.com/rbenv/rbenv/pull/1568) to make the necessary changes to bashrc/zshrc/etc _itself_ rather than printing the instructions for users to perform manually.

This new behavior is not released yet; and so the homebrew installation does not yet take advantage of it. What's more, rbenv's README instructions reflect the latest code _on rbenv's main branch. So if you view https://github.com/rbenv/rbenv#installation, you'll be seeing the installation steps that presume the still-unreleased behavior. 😬 

I apologize for the confusion caused. I suspect most of this confusion should be sorted out once the next release is cut. Then the readme will be applicable and homebrew's installation will be able to take advantage of the streamlined install behavior.

**Comment by murfel** [comment]
Ah, I see, thank you! I'll stop stepping on your toes :)

**Comment by jasonkarns** [comment]
If you don't mind, I think I'd like to keep this open until the next release. There might still be some improvement to the messaging between the readme, homebrew messaging, and rbenv init.

**Comment by mislav** [comment]
Closing since the new release is out: https://github.com/rbenv/rbenv/releases/tag/v1.3.0

The setup instructions now boil down to: just run `rbenv init` (optionally specifying your shell or shells as arguments) and rbenv will edit the shell initialization files for you to bootstrap itself into any new instance of that shell. This simplifies the README instructions, which are now clearer, as well as the [rbenv-installer](https://github.com/rbenv/rbenv-installer) script which is now fully automated and relies on no user setup steps.
