### ISSUE TITLE
Using releases with git clone installation

### ISSUE THREAD

**Issue by mohamedhafez** [rbenv/rbenv#1578]
When using the `git clone` installation, if we wanted, we could get the stability of running only releases of rbenv instead of just using head by doing `git checkout` of the tag of the latest release, correct? Maybe that should be added in the README if so?

**Comment by mislav** [comment]
Hi, the git clone method of installing and keeping rbenv up to date is really meant to be always running the bleeding edge version of the project, which is meant to be stable. If you want to only checkout releases, you could checkout a git tag by using `git checkout -q v1.3.0`, but whoever did that would have to manually check out newer tags upon releases.

In theory, this project could consider having "stable" branches like `1.3-release` that users could check out and receive only fixes going forward, but no breaking changes, but I never felt a strong motivation to maintain stable branches, especially when we have a very good track record of keeping `master` stable for over 10 years.

Ultimately, if a person wants to only use packaged releases of rbenv, they should use a package manager such as Homebrew or whatever comes with their operating system, provided that the community maintains packages in those repositories. Officially, only the Homebrew package is maintained along with this project.

Closing since I believe I answered your question. My conclusion is that the git clone method is unsuitable for most users to be tracking anything else other than the main branch of this repository.

P.S. thanks for pinging me about a release. I was meaning to release for some months now.
