### ISSUE TITLE
rbenv init doesn't work properly on WSL

### ISSUE THREAD

**Issue by wafcio** [rbenv/rbenv#1594]
I have tried to install a new rbenv, and with the new README, it doesn't work.

I believe some issue could be here: https://github.com/rbenv/rbenv/blob/c335ab83de40d48093870d300de52c61bbd68359/libexec/rbenv-init#L91
because I see the text "skipped .bashrc already configured for rbenv." even though I don't have rbenv in .bashrc.

I commented out this whole if, added the script to .bashrc, and the command `rbenv` started working.

Unfortunately, I couldn't install the ruby-build plugin because the plugin's directory doesn't exist.

**Comment by mislav** [comment]
Hi, which operating system are you running under WSL?

It's strange that you had to comment out the `grep` line. The grep utility should typically not return a success status unless it matched the pattern in question. Could you try running `grep "nonexist" ~/.bashrc && echo FOUND` and see what that prints? It should print "FOUND" only if the word "nonexist" was found in the file in question.

> Unfortunately, I couldn't install the ruby-build plugin because the plugin's directory doesn't exist.

The official instructions to install the ruby-build plugin are:

```
git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build
```

The way `git clone` works is: if the destination directory does not exist, it should be automatically created. Thus, you do not have to create the `~/.rbenv/plugins` directory manually. However, if `git clone` still fails due to directory being missing, maybe it's a very old version of git? You could try making an empty directory manually with `mkdir -p "$(rbenv root)"/plugins`

**Comment by wafcio** [comment]
I wish to recover the previous way of rbenv setup, which was much easier, a bit more manual work, but bigger control over the whole process.

**Comment by mislav** [comment]
> ```
> $ ~/.rbenv/bin/rbenv init
> skipping ~/.bashrc: already configured for rbenv.
> $ rbenv
> Command 'rbenv' not found
> ```

Hi, thanks for updating the thread. Note that after you run `rbenv init`, you will have to reload your shell (or terminal window) so that the changes to shell initialization files take effect. Just running `rbenv` right after `rbenv init` in the same shell will not work.

Can you check the contents of bashrc and see if rbenv-related lines are there? And if rbenv doesn't work even after reloading your shell or terminal window, then see if you have a bash_profile file and move those lines there instead. Bash is weird in the way that it either loads bashrc or bash_profile depending on how the shell is being launched, which differs between operating system and setups.

> I wish to recover the previous way of rbenv setup, which was much easier, a bit more manual work, but bigger control over the whole process.

The more manual process never went away. For bash, you could add this to your `~/.bashrc` or `~/.bash_profile`:

```
eval "$(rbenv init - --no-rehash bash)"
```

For zsh, I'm sure you know where to place it, just remember to change the shell type from "bash" to "zsh". [See here for more information](https://github.com/rbenv/rbenv/blob/master/README.md#how-rbenv-hooks-into-your-shell)

**Comment by wafcio** [comment]
I remember that in the past, in README there was information like 
`export PATH="$HOME/.rbenv/bin:$PATH"

eval "$(rbenv init - bash)"`

**Comment by wafcio** [comment]
After I have added it manually to .bashrc then it started working. Please bring it back in README

**Comment by mislav** [comment]
> Please bring it back in README

I already did based on your comments earlier today: https://github.com/rbenv/rbenv/commit/a43095dc1133eeb58eb53cd17e6a00cebad7a5e3

I will close this issue as your problem seems to be resolved and our README is improved as the result. Thanks for the feedback!
