### ISSUE TITLE
Is it possible to install rbenv along with rvm in same machine?

### ISSUE THREAD

**Issue by manganapathy** [rbenv/rbenv#1595]
Hello, 
In our organization, some teams utilize rbenv while others employ RVM to manage Ruby. Is it feasible to have both tools installed on the same machine?

**Comment by mislav** [comment]
Hi, the short answer is, no you can not reliably utilize rbenv and RVM on the same machine. This is because these tools utilize different mechanisms for switching between versions when you run Ruby programs, and those mechanisms would compete with each other and inevitably cause problems for the user somewhere down the line.

More detailed: RVM is typically loaded in one's interactive shell and overrides calls to `ruby`, `bundle` and other Ruby-related commands with shell functions that handle version-switching. On the other hand, rbenv places itself in PATH and adds shims (or command wrappers) like `ruby` and `bundle` to handle switching. If both of these tools are present and loaded on the same system, RVM would typically "win" (as in, take precedence), resulting in rbenv effectively not functioning.

The only way to effectively utilize RVM and rbenv on the same system would be to only load one of them into a shell environment on-demand, and only per-project. But, this way of usage would be highly uncommon and would require a certain degree of expertise and discipline from the user.

Closing because I believe I answered your question!
