### ISSUE TITLE
can't rehash, .rbenv shims exists, but it doesn't

### ISSUE THREAD

**Issue by jrochkind** [rbenv/rbenv#238]
I'm using a shared install of rbenv as per https://github.com/sstephenson/rbenv/wiki/shared-install-of-rbenv

In general, it was working, when I only had one ruby installed. But now I installed a jruby too, and have set it using `rbenv shell`. 

And for some reason rbenv rehash ain't working when jruby is active. 

``` bash
bash-3.2$ rbenv rehash
rbenv: cannot rehash: /usr/local/rbenv/shims/.rbenv-shim exists
bash-3.2$ ls -l /usr/local/rbenv/shims/.rbenv-shim
ls: /usr/local/rbenv/shims/.rbenv-shim: No such file or directory
```

Any ideas of where I should start troubleshooting here?

**Comment by joffotron** [comment]
I'm still seeing this, and doing a bit of debugging, I change the 
```sh
{ echo > "$PROTOTYPE_SHIM_PATH"
} 2>/dev/null ||
{ echo "rbenv: cannot rehash: $PROTOTYPE_SHIM_PATH exists"
  exit 1
} >&2
```

block to simply `echo > "$PROTOTYPE_SHIM_PATH"`

I then confirm that the .rbenv-shim file does not exist before running `bundle install`, and I get: e.g:

```
Using sunspot 2.0.0 from git://github.com/redbubble/sunspot (at reenable-get-requests-2-0-0)
Using sunspot_rails 2.0.0 from git://github.com/redbubble/sunspot (at reenable-get-requests-2-0-0)
/opt/boxen/rbenv/libexec/rbenv-rehash: line 19: /opt/boxen/rbenv/shims/.rbenv-shim: cannot overwrite existing file
```

The file is then removed by the script in the `remote_prototype_shim()` function after.

Is there some kind of race condition, or double execution happening here?

**Comment by mislav** [comment]
Do you have the `gem-rehash` plugin? Which version of Bundler? Which version of Rubygems? Is Bundler configured to run multiple jobs in parallel? Check `$BUNDLE_JOBS` environment variable. Thanks

**Comment by joffotron** [comment]
* Yes, I have the `gem-rehash` plugin installed
* Bundler 1.6.6
* Rubygems 2.2.2
* `$BUNDLE_JOBS` is set to 8.

Doing a `BUNDLE JOBS=1 bundle install` makes the problem go away, so it looks like that's the culprit

Is this aspect of rbenv basically incompatible with that setting, or is there something else we can do...?

**Comment by mislav** [comment]
I'm trying to bake gem-rehash functionality into rbenv core, but for that I wanted to cure it of its parallelism problem. I couldn't solve the Bundler jobs problem; see WIP changeset and commit message here https://github.com/sstephenson/rbenv/compare/bundle-rehash

**Comment by jschank** [comment]
I had this problem too, and for me the problem was that I had installed fish, with homebrew, and used the --HEAD option. Apparently when you do this, updating/upgrading doesn't work. For me I had to uninstall fish, and then reinstall it to get to the latest. (at the time that was fish 2.2.0) And that solved it for me.

Others may benefit from checking this

**Comment by lacostenycoder** [comment]
What is the current state of this?  I'm not able to run rehash now..

**Comment by mislav** [comment]
@lacostenycoder Automatic rehash after `gem install` is now a part of rbenv. How are you not able to run rehash? Are there error messages? Which executable were you expecting to be available after rehash? Is there a `` `rbenv root`/shims/.rbenv-shim `` file?

**Comment by raventid** [comment]
Hey, @mislav. I suppose I might met the same problem. But I am not sure, perhaps it is expected behaviour.

I've switched from rvm to rbenv yesterday. So I am using rbenv 1.0.0-19-g29b4da7. And Ruby 2.3.0.

I've set 2.3.0 as global.

I've installed bundler. $ gem install bundler.

**If I call bundler directly from my project I cannot find it.**
```
julian@julian-dell:~/best_quotes$ bundle install
The program 'bundle' is currently not installed. You can install it by typing:
sudo apt-get install bundler
```

**This one is works**
`julian@julian-dell:~/best_quotes$ rbenv exec bundle install`

**My shims folders looks like this and .rbenv-shim is empty, also I cannnot run rbenv rehash because **

> rbenv: cannot rehash: /home/julian/.rbenv/shims/.rbenv-shim exists

.
```
julian@julian-dell:~/.rbenv/shims$ ls -la
total 36
drwxrwxr-x  2 julian julian 4096 Mar  8 12:51 .
drwxrwxr-x 12 julian julian 4096 Mar  7 20:43 ..
-rwxrwxr-x  1 julian julian  399 Mar  7 20:22 erb
-rwxrwxr-x  1 julian julian  399 Mar  7 20:22 gem
-rwxrwxr-x  1 julian julian  399 Mar  7 20:22 irb
-rwxrwxr-x  1 julian julian  399 Mar  7 20:22 rake
-rw-rw-r--  1 julian julian    0 Mar  7 23:18 .rbenv-shim
-rwxrwxr-x  1 julian julian  399 Mar  7 20:22 rdoc
-rwxrwxr-x  1 julian julian  399 Mar  7 20:22 ri
-rwxrwxr-x  1 julian julian  399 Mar  7 20:22 ruby
```

```
julian@julian-dell:~/.rbenv/shims$ gem list

*** LOCAL GEMS ***

bigdecimal (1.2.8)
bundler (1.11.2)
dhh (0.1.0)
did_you_mean (1.0.0)
io-console (0.4.5)
json (1.8.3)
minitest (5.8.3)
net-telnet (0.1.1)
power_assert (0.2.6)
psych (2.0.17)
rack (1.6.4)
rake (10.4.2)
rdoc (4.2.1)
test-unit (3.1.5)
```

I guess I should not call rbenv exec explicitly every time, yes?

**Comment by mislav** [comment]
@raventid You should delete the `.rbenv-shim` file (which shouldn't have been there) and run rehash again. That should pick up the `bundler` shim and allow you to invoke bundler.

**Comment by tdegrunt** [comment]
Seeing the same problem, there's no `.rbenv-shim` file, but the shim folder doesn't include all executables.

Had servers where the correct shims where installed, and some where it wasn't: 

Output of .bundle/config:
```
root@all1:/data/server# cat .bundle/config 
---
BUNDLE_FROZEN: '1'
BUNDLE_PATH: vendor/bundle
BUNDLE_DISABLE_SHARED_GEMS: '1'
BUNDLE_WITHOUT: development:test
BUNDLE_BIN: bin
```

On a working server i found this:
```
root@api3:/data/server# cat .bundle/config 
---
BUNDLE_WITHOUT: development:test
BUNDLE_BIN: bin
```

So, I'm guessing my problem has to do with the fact  `--deployment` was used with bundler?

**Comment by mislav** [comment]
@tdegrunt Yes. With `bundle install --deployment`, all gems from the bundle are not installed in the default gem location, but to `vendor/bundle` within the project's root directory. In this case, rbenv doesn't pick up the gem executables. Instead, you should use `bundle exec rake …` to run the executables for this project, or you can add `--binstubs` to install the binstubs for this project in `./bin` directory. Either way, rbenv will not pick up those executables as part of its `rbenv rehash` process because there is no need to.

**Comment by tdegrunt** [comment]
Thanks @mislav for your answer. It would still be handy if rbenv would pick it up though, it's easier to do `puma` than `bundle exec puma`. Could you elaborate a little on why there is no need to? (Just trying to understand).
