### ISSUE TITLE
After Homebrew rbenv install gem tries to install to /Library

### ISSUE THREAD

**Issue by ryanburnett** [rbenv/rbenv#463]
I'm running Mac 10.8.5 with Xcode and Command Line Tools installed. As the guide recommended, I installed rbenv via Homebrew. After a successful `rbenv install 2.0.0-p247` I tried to install Compass:

`gem install compass`

…but something's off because it's trying to install to /Library:

`ERROR:  While executing gem ... (Gem::FilePermissionError)
You don't have write permissions for the /Library/Ruby/Gems/1.8 directory.`

Here are my troubleshooting answers:

`which rbenv`
`/usr/local/bin/rbenv`

...and:

`echo $PATH | grep --color=auto "$(rbenv root)/shims"`
`/Users/Ryan/.rbenv/shims:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/Ryan`
(`/Users/Ryan/.rbenv/shims` is in red)

My `~/.bash_profile` contains only this:

`eval "$(rbenv init -)"`

Here's my Gist:
https://gist.github.com/ryanburnett/6894645

Thanks for your help.

**Comment by jagorski92** [comment]
Hoping to resurrect this thread. I am having the exact same issue, however I am new to Ruby (and the command line in general) and am not sure how to set ruby as the default global version or how to avoid the permissions error. I get it whenever I want to update ruby or make any other changes, probably because it is installed in the system. There is no local version at the moment. 

My current $PATH (with user "XXX"):

/Users/XXX/.rbenv/shims:/Users/XXX/.rbenv/bin:/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

My current bash profile:

export PATH="/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:$PATH"

export RBENV_ROOT="$HOME/.rbenv"

if [ -d $RBENV_ROOT ]; then
  export PATH="$RBENV_ROOT/bin:$PATH"
  eval "$(rbenv init -)"

Please let me know how to go forward. It looks like I can install GEMs but can't do anything else without encountering the permissions notification as described earlier in this thread. Thanks!

**Comment by mislav** [comment]
@jagorski92 Your setup seems fine. What you might be missing, though, is installed Ruby versions other than "system". Check your `rbenv versions`, and if there's no other versions than "system", install some using `rbenv install` (you'll need the ruby-build plugin first).

Then, switch to a Ruby version other than "system", e.g. `rbenv local 2.3.0`, then `gem install` or `bundle install` or anything that you need to do.

**Comment by jagorski92** [comment]
You are correct, I seem to only have it installed on "system". I'm a total noobie here so I'm not 100% sure how to install a local/non-system version onto my computer using the command line. Would you mind telling me how (or providing a link to a site that explains how to create a local version)? Thanks so much!

**Comment by mislav** [comment]
@jagorski92 It's all [described in the readme](https://github.com/rbenv/rbenv#installing-ruby-versions).

**Comment by commscheck** [comment]
If you're coming to this thread (like me) because you've:

- freshly installed rbenv
- run `rbenv install 2.4.1` (or another version)
- selected a version with `rbenv global 2.4.1` or `rbenv local 2.4.1`

but you're still getting a file permission error, make sure that you've run `rbenv init` and followed its instructions. I missed it during the install process and was running into this issue.

**Comment by nicksinai** [comment]
I had this issue on Mac and found that my solution was as @mislav suggested. However, remember to close terminal and reopen after running `rbenv global 2.4.1` or `rbenv local 2.4.1` so that these changes take effect.

**Comment by kevinSuttle** [comment]
Thanks @commscheck!  For me, making sure I had `eval "$(rbenv init -)"` in my .zshrc and _then_  restarting the shell via  `exec $SHELL -l` was what did the trick.

**Comment by synchronizing** [comment]
In my case it seems that the installed Ruby version was somehow corrupt. Re-installed it via `rbenv install 2.6.5`, opened new terminal, and all is working. Found same issue in https://github.com/rbenv/rbenv/issues/1181.
