### ISSUE TITLE
Thoughts on an 0.5.0 release?

### ISSUE THREAD

**Issue by parkr** [rbenv/rbenv#609]
Heya, love what you've done with the place.

Was bouncing around the repo, enjoying the new issues layout and noticed that there have been 98 commits to `master` since v0.4.0 and that v0.4.0 was tagged in January of 2013. I know rbenv is already really stable, but what do you think about pushing out a v0.5.0 soonish? No need?

Just thought I'd start a conversation. :smile:

**Comment by kenips** [comment]
hey @mislav I know that there are tonnes of issues opened for this and it's reasonable that it should ship when it's ready. But... we're in 2015 now so isn't it fair to put a milestone up or something?

**Comment by mislav** [comment]
@kenips Yep, gearing up for that. The master version is pratically ready. I have added the few remaining issues/PRs to [the 1.0 milestone](https://github.com/sstephenson/rbenv/milestones/1.0).

The holdup is the migration path. Specifically, I want to make a script that you can use for updating rbenv that would also warn you about obsolete or dangerous plugins. It would also detect common installation problems, such as duplicate installs of either rbenv or ruby-build. Finally, the same script could be used to extract environment information so that users could report bugs more reliably.

**Comment by kenips** [comment]
Lovely!! Glad to hear. This will be incredibly great to those who use packages since they only get tagged versions :). Awesome work x100000 :beers: :
