### ISSUE TITLE
puppet: command not found

### ISSUE THREAD

**Issue by andreicristianpetcu** [rbenv/rbenv#634]
Hi! I installed puppet gem and I think it should have a executable like rails or rake. On a non-rbenv environment this works.

ls -la ~/.rbenv/shims/|grep puppet
No puppet shim

rbenv rehash                                                                                                                                                               rbenv: cannot rehash: /home/andrei/.rbenv/shims/.rbenv-shim exists

Am I using rbenv wrong? Thank you!

**Comment by munikiran-hcl** [comment]
not useful.....

when i am running the puppet agent command or puppet  i am getting the puppet command not found.

no idea what went wrong, only thing is i am using the ec2 free tier rhel instance and it doesnt have the subscription, because of this the puppet command is not found? if yes, what is the resolution?
