### ISSUE TITLE
possible spin-off project to support shims for other languages?

### ISSUE THREAD

**Issue by sbull** [rbenv/rbenv#709]
I've been a fan of `rbenv` since the beginning, preferring the shim approach over manipulation of shell builtins.

I'm also using `nvm` now, and I'd love to have the specified node version be picked up automatically based on the project directory without needing to run `nvm use` manually. This is deemed to be outside the scope of the nvm project itself (https://github.com/creationix/nvm/issues/110#issuecomment-16469680). It seems like having a shim for node would fix this.

To that end, I'm wondering if there would be any support for a spin-off project do general-purpose binstub/shim creation in other languages? As far as I can tell, https://github.com/sstephenson/rbenv/blob/master/libexec/rbenv-rehash and https://github.com/yyuu/pyenv/blob/master/libexec/pyenv-rehash are still quite similar (I'm sure intentionally so). Would there be any support for a shared version of this that is more generic, and perhaps uses a few variables at the top to specify differences (e.g. `EXE_NAME=rbenv` vs. `EXE_NAME=pyenv`).

Thoughts?

\cc @yyuu

**Comment by jasonkarns** [comment]
For node, there is a direct port: [nodenv](https://github.com/OiNutter/nodenv)

**Comment by mislav** [comment]
For PhantomJS, there is [phantomenv](https://github.com/wfarr/phantomenv).

Yes, there seems to be a trend and a need for an agnostic version switcher. I was hoping to work on one in my spare time, although I can't promise anything yet this early.

**Comment by mislav** [comment]
@sbull Your idea for a project that supports shims for multiple languages is good, but right now I'm focused and wrapping up rbenv 1.0 and getting it out the door, and this issue tracker is not a place where I'd want to store ideas about possible spin-off projects.

Maybe post these ideas to [mislav/anyenv](https://github.com/mislav/anyenv), a Go clone of rbenv that can manage versions of anything that you configure it for. I still have to work on that project to make it more user-friendly, since it's just a proof-of-concept right now, but it's blazing fast and 99% feature-compatible with rbenv, with exception of plugin support.
