### ISSUE TITLE
Add global ruby version shim/alias that points to respective directory in ~/.gem/ruby

### ISSUE THREAD

**Issue by ryanburnett** [rbenv/rbenv#880]
I'm running ruby 2.3.0 in rbenv. `echo $PATH` returns:
```
/Users/Ryan/.rbenv/shims /usr/local/git/bin /usr/local/git/bin /Users/Ryan/.rbenv/bin /Users/Ryan/.gem/ruby/2.3.0/bin /usr/bin /bin /usr/sbin /sbin
```

Due to [new security restrictions in El Capitan](http://stackoverflow.com/questions/31972968/cant-install-gems-on-os-x-el-capitan), I installed my gems, compass and sass like so:

```
gem update --system --user-install
gem install compass --user-install
gem install sass --user-install
```

...this installs them to `~/.gem/ruby/2.3.0/bin`. I had to add this to my $PATH to get compass and sass working.

My concern is that each time I upgrade my rbenv ruby I'll need to manually update my path accordingly. 

Is there any way in rbenv to add a shim/alias that uses my global ruby version and points to its respective directory in ~/.gem/ruby?

Thank you.

* OS X 10.11.3
* rbenv 1.0.0-19-g29b4da7
* ruby 2.3.0p0
* Compass 1.0.3
* Sass 3.4.21

P.S. rbenv is amazing - keep up the great work!

**Comment by mislav** [comment]
> Is there any way in rbenv to add a shim/alias that uses my global ruby version and points to its respective directory in ~/.gem/ruby?

There are many ways to approach what you're doing and your workaround is just as valid. There are no official ways that rbenv expects you to do this. Bear in mind that rbenv doesn't currently support `~/.gem` install location and that's why you needed to add its `bin` directory to your PATH. My recommendation is that you add that directory higer than rbenv's `shims` directory, otherwise your approach will stop working if you install Compass or Sass in any rbenv-managed version without using `--user-install`.

**Comment by ryanburnett** [comment]
Thanks @mislav - keep up the great work!
