### ISSUE TITLE
'Friendly' Names

### ISSUE THREAD

**Issue by civik** [rbenv/rbenv#894]
Is there any capability for rbenv to provide a name other than the version number for the ruby installs?

**Comment by rafmagana** [comment]
No that I'm aware of, it'd be a nice feature to have, it's really annoying having to write the version always.

**Comment by jeremy** [comment]
> Is there any capability for rbenv to provide a name other than the version number for the ruby installs?

You're free to provide your own version names, considering it's "just" a directory. For example:
```bash
$ ln -s ~/.rbenv/versions/2.3.1 ~/.rbenv/versions/2.3
$ readlink ~/.rbenv/versions/2.3
/Users/jeremy/.rbenv/versions/2.3.1
$ echo $RBENV_VERSION
2.3
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
```

> having to write the version always

Do you write this version a lot? Are you using the builtin bash/zsh completion?

**Comment by rafmagana** [comment]
@jeremy I do use completion and I use .ruby-version which makes things easier, and yet there're some case where I have needed to "scroll" among all the versions I have to select a specific version, not a big deal though. I like the directory name trick for some cases but I wouldn't do that since I'd still need to "scroll" but it's definitely a good workaround when one uses just a few versions. 

This issue says "friendly names" but I was thinking more about aliases or shortcuts, something like: 

* `rbenv shell 2` to pick the highest version of 2.x.x
* `rbenv shell 2.2` same but for 2.2.x
* `rbenv shell rbx` for Rubinius
* `rbenv shell jr`, for jruby

and so on. Probably something not that useful for others but I'd like something like that, I'll try to put something together and create a PR as soon as I can. Thanks.

**Comment by jeremy** [comment]
@rafmagana [rbenv-use](https://github.com/rkh/rbenv-use) sounds right down your alley 😁

It uses internally [rbenv-whatis](https://github.com/rkh/rbenv-whatis) to fuzzy-match friendly names/shortcuts to specific Ruby versions.

**Comment by rafmagana** [comment]
@jeremy WOOOOW, didn't know about that, thanks a lot!!!

**Comment by jasonkarns** [comment]
@ELLIOTTCABLE nodenv-aliases was actually a fork of rbenv-aliases, so this feature should work as expected with the plugin: https://github.com/tpope/rbenv-aliases
