### ISSUE TITLE
Are rbenvs cp-safe?

### ISSUE THREAD

**Issue by snakescott** [rbenv/rbenv#903]
Sorry in advance if this is obvious, clearly documented, or if this is the wrong forum for this question. I made sure to review the repo README, check for a mailing list, and Google before filing.

Is it safe to copy an rbenv via "cp -r old_rbenv_dir new_rbenv_dir"? Or, for example, is this not the case due to absolute paths inside the rbenv.

See e.g. http://virtualenvwrapper.readthedocs.io/en/latest/command_ref.html#cpvirtualenv

Thanks!

**Comment by mislav** [comment]
This is an interesting question. What do you mean by "old_rbenv_dir" and "new_rbenv_dir", exactly? If it's the top-level directory where rbenv stores its files (`~/.rbenv` by default), for the most part moving it elsewhere should work, but moving the Ruby versions itself (`~/.rbenv/versions/*`) will likely not work due to Rubies usually being compiled with hardcoded paths.

However, you can move to a new rbenv directory, leave the installed Rubies at the old location, and symlink them into `/path/to/new_rbenv_dir/versions/*`. That should work.
