### ISSUE TITLE
Not clear that $RBENV_ROOT needs to be set

### ISSUE THREAD

**Issue by wiredin** [rbenv/rbenv#917]
I installed rbenv into a folder other than $HOME and ran into something that was not clear.

I installed rbenv and then installed ruby-build into the plugins folder of rbenv.

but `$rbenv install` still said "Not Found" 
I reloaded my .bash_profile and opened a new terminal session... still `$rbenv install` could not be found.

Then I went through rbenv-install file in /plugins and saw `$RBENV_ROOT`. I realized `$RBENV_ROOT` was not set, so I set it.

setting `$RBENV_ROOT` was not part of the instructions, should it be?

**Comment by schlueter** [comment]
Installing in a non standard directory (i.e. not ~/.rbenv) is not covered in the README, and therefore I don't see why use of *RBENV_ROOT* should be expected to be covered; additionally, in the [Evironment Variables section](https://github.com/rbenv/rbenv#environment-variables) the *RBENV_ROOT* variable is described, perhaps not clearly enough though.

**Comment by mislav** [comment]
The explanation by @schlueter is correct. Because you're installing in a non-standard directory, you will need to read the entire README, including the part about RBENV_ROOT.

**Comment by vduseev** [comment]
For anyone wondering what must be done to install Ruby versions with `rbnev` as a system wide installation. This flow was tested with macOS:

1. Install rbenv to `/opt/rbenv` using GitHub checkout
2. Add `export RBENV_ROOT=/opt/rbenv` and `export PATH="$RBENV_ROOT/bin:$PATH"` to your `.bash_profile`
   Note, that Linux initializes bash with `.bashrc` instead of `.bash_profile`
3. Manually install ruby-build to `/opt/rbnev/plugins/` using GitHub checkout
4. Manually initialize rbenv in the terminal: `eval "$(sudo -E rbenv init --)"`. This one's important. This preserves your environment variables (the non-standard RBENV_ROOT path) and creates the `versions` and `shims` directories in the location only writable by root user.
5. Install new Ruby verions: `sudo -E rbenv install 2.6.0`
6. Profit
