### ISSUE TITLE
This does not install

### ISSUE THREAD

**Issue by bradennapier** [rbenv/rbenv#920]
```
-bash: src/configure: No such file or directory
Braden:.rbenv bradynapier$ rm -fr ~/.rbenv
Braden:.rbenv bradynapier$ git clone https://github.com/rbenv/rbenv.git ~/.rbenv
fatal: Could not get current working directory: No such file or directory
Braden:.rbenv bradynapier$ touch ~/.rbenv
Braden:.rbenv bradynapier$ git clone https://github.com/rbenv/rbenv.git ~/.rbenv
fatal: destination path '/Users/bradynapier/.rbenv' already exists and is not an empty directory.
Braden:.rbenv bradynapier$ 
Braden:.rbenv bradynapier$ rm -f ~/.rbenv
Braden:.rbenv bradynapier$ git clone https://github.com/rbenv/rbenv.git ~/.rbenv
fatal: Could not get current working directory: No such file or directory
Braden:.rbenv bradynapier$ 
```

When trying to clone it says that directory doesnt exist... so I add it then it says error that file already exists... LOL!?

**Comment by schlueter** [comment]
This appears to be a local issue with your system, not one with rbenv. 

I hate to ask it (because I'll sound like a T1 at a mediocre network provider), but could you reboot (if you *really* can't, log out and back in again, and if that's not even possible, open a new terminal session, and please state which you did) your machine and provide the output of `ls -Al`.
