### ISSUE TITLE
jruby install artifact url fails, times out, then skips to a different url

### ISSUE THREAD

**Issue by detj** [rbenv/rbenv#931]
I'm not sure if this is clearly an `rbenv` issue or not. I tried installing jruby using rbenv by running

```
$ rbenv install jruby-9.1.2.0
Downloading jruby-bin-9.1.2.0.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/60598a465883ab4c933f805de4a7f280052bddc793b95735465619c03ca43f35
```

And it got stuck at that line. I checked network transfer in Activity Monitor to see if its really transferring data, it was not. Finally, after a very long time, ~15 to 20 mins — _from what it felt, didn't actually measure_, it times out and switches to a different URL. jruby from the second URL installs fine.

```
error: failed to download jruby-9.1.2.0.tar.gz
-> https://s3.amazonaws.com/jruby.org/downloads/9.1.2.0/jruby-bin-9.1.2.0.tar.gz
Installing jruby-9.1.2.0...
Installed jruby-9.1.2.0 to /Users/detj/.rbenv/versions/jruby-9.1.2.0
```

So, is this really anything to do with rbenv, or should I report this bug to jruby ?
Also, it would be great, if someone could throw some light on who's actually managing the CloudFront account and how the fallback mechanism in `rbenv install` works.

**Comment by detj** [comment]
Anyone has any insight on this?

**Comment by mislav** [comment]
Sorry for the late reply. The CloudFront mirror is ours and is managed by Basecamp, where Sam who created this project works. This sounds like it was a network glitch regarding the mirror. You could report this issue in the ruby-build project, which handles these downloads and installation, but since no other people are reporting this, I think this would be just an intermittent error. If this keeps biting you, please open an issue there!

**Comment by detj** [comment]
Got that! Thanks @mislav
