### ISSUE TITLE
Getting bundler issue with rbenv chef-client

### ISSUE THREAD

**Issue by Princetambar** [rbenv/rbenv#951]
I am running chef-client with sudo and getting below error 

The `bundle' command exists in these Ruby versions:
  2.1.0

i had 2.1.0 ruby installed ,now i am migrating to 2.3.1 , for that i installed 2.3.1 also using rbenv. when i run chef-client after sudo su - then i am getting above mentioned error . i dont know why its not picking bundler from 2.3.1. 

can anyone help me how i can install bundler for 2.3.1 also?? quick help will be appreciated

**Comment by mislav** [comment]
How to install a gem for a specific version:

```sh
RBENV_VERSION=2.3.1 gem i bundler --no-rdoc --no-ri
```

**Comment by Princetambar** [comment]
bundler gem is already there under  /usr/local/rbenv/versions/2.3.1/..... .

**Comment by Princetambar** [comment]
it was installed but i dont know why its not picking from 2.3.1

**Comment by mislav** [comment]
Note that when you use `sudo`, the command executes in a different environment than one where you called `sudo` from. You'll need to configure both environments properly for rbenv. Unfortunately, I can't help you with that, because I can't see what's going on on your system.

For starters, it seems like you changed your RBENV_ROOT to `/usr/local/rbenv` in your main environment. You have to ensure that RBENV_ROOT it set to the same location for the root user as well.
