### ISSUE TITLE
Suggested deployment model should caution against ownership/writability of home directory

### ISSUE THREAD

**Issue by charles-dyfis-net** [rbenv/rbenv#954]
Ideally, a production instance of a daemon interacting with untrusted users should not be able to alter that program's code, or the code of any dependency thereto: The set of files writable by a daemon should be limited to *data*, and not code (or any data which can be interpreted as code). Traditionally, standard users (such as `nobody`, `bin`, `daemon`) created for daemon use tend to have home directories such as `/`, which those daemons cannot themselves write to; or the daemons tend to be directly `exec`'d in a manner not involving any intervening shell or other code which would honor or evaluate dotfiles.

[Deploying with rbenv](https://github.com/rbenv/rbenv/wiki/Deploying-with-rbenv) suggests using `~/.rbenv` (in the home directory of the user as which a daemon is running), without any cautions regarding ownership or writability of this directory. If followed without appropriate precautions, this ensures an easy mechanism for any exploit gaining the permissions a given application to be able to modify the runtime environment of, or otherwise persistently inject code to, future instances of that application.

**Comment by mislav** [comment]
You're right. However, it's not our responsibility to provide users with a solid deployment guidelines. The article that you linked to is meant only as an example how deployment to a non-shared server can be similar to installing locally. Users are responsible to do their due dilligence re: securing their own server.

We could easily make more complex documentation, but more complex documentation means more people failing to follow it and then opening support questions in this repo, because they don't know how to deal with permissions on their own server. I want to distance myself as far as possible from giving this kind of support as it consumes my free time.

Do you have suggestions to improve the article in a way that is more secure, but is not significantly more complex to set up?
