### ISSUE TITLE
Conflicting gem versions causes Gem:LoadError

### ISSUE THREAD

**Issue by dineshkumar-cse** [rbenv/rbenv#965]
Hi, I've two projects which uses same ruby version but have different gem dependency. The gem version can't be controlled as its a dependency of other gem.

i.e i've jbundler (with specific version) which depends on jar-dependencies. so **Project1 has `jar-dependencies 0.3.5`, Project2 uses recent `jar-dependencies 0.3.10`**

So i get the following error:
`Gem::LoadError: You have already activated jar-dependencies 0.3.5, but your Gemfile requires jar-dependencies 0.3.10`

I know that in rvm i won't be having the issue, since we can configure separate gemset for each project. In rbenv is there a way to solve this? i'm using rbenv version 1.0.0.

Also the philosophical question why rbenv chose to share gems rather than having different versions for each project, ofcourse most times its reusable and less gems, and memory usage. but these kindof issues pops up and i assume it would 've been though of?

**Comment by mislav** [comment]
> Also the philosophical question why rbenv chose to share gems rather than having different versions for each project

Rbenv didn't exactly choose to "share" gems; it chose not to care about gems at all. It only helps install and switch between Ruby versions per-projects. Everything else is the responsibility of tooling within individual projects.

In Ruby world, we have perfect tooling to help us keep gems separate between projects, and it's called Bundler. I see that you're already using Bundler, because your error message mentiones a `Gemfile`. With Bundler, the concept of separate gemsets for each project is not needed.

With bundler, you simply `bundle install` (you can also add something like `--path vendor/bundle` to keep all installed gems contained within the project's directory), and then use `bundle exec <command>` for any command such as `rails`, `rake`, and so on.

The fact that you got the above `Gem::LoadError` means that something within your project tried to load a gem manually or outside of Bundler, which shouldn't be allowed. You might have also forgotten to use `bundle exec`. In any case, this isn't something that rbenv is concerned with or designed to solve.

**Comment by dineshkumar-cse** [comment]
I've used bundle exec `whatever command`

**Comment by mislav** [comment]
Sorry, I'm not familiar with `jbundle`, which seems to be a separate project to Bundler. You might want to take this dicussion to somewhere where people with more experience with jbundle are. Perhaps on the jbundle project itself, because this might be a bug? If you're doing that, they will likely need you to provide more detail to them.

**Comment by dineshkumar-cse** [comment]
This is not specific to a particular gem or jbundler, The issue will rise even when we run `rails console` or `rake` etc. if there's an existing different version of gem in current rbenv ruby version.

**Comment by mislav** [comment]
> If there's an existing different version of gem in current rbenv ruby version

If there's an existing different version of gem in Ruby, that alone isn't a problem. The problem is that *something* loaded `jar-dependencies` before Bundler (or jbundle) had a chance to even execute. And thus, the version loaded was wrong. You will have to find out what exactly loads `jar-dependencies` in your current setup.
