### ISSUE TITLE
How to set `GEM_HOME` for `system` Ruby but not for other versions?

### ISSUE THREAD

**Issue by reitermarkus** [rbenv/rbenv#975]
On macOS, the default `system` Ruby needs `sudo` to install Gems, but now, when I set `GEM_HOME`, `rbenv` will install Gems for *any* version inside `GEM_HOME`, instead of keeping separate directories for each Ruby version.

How can I set a custom `GEM_HOME` for only the `system` Ruby?

**Comment by jeremy** [comment]
If you're setting `GEM_HOME` so you can install gems without needing to sudo, I'd recommend using `gem install --user-install` instead.

**Comment by Nakilon** [comment]
@jeremy does rbenv install gems per ruby version with that `--user-install` flag?

**Comment by jeremy** [comment]
RubyGems installs to `Gem.user_dir` when `--user-install` is passed. I did a web search for docs and took at look at the code on GitHub, and user_dir does include the Ruby version. Check out http://guides.rubygems.org/faqs/#user-install, for example.

Note that you have `--install-path` and `--bin-path` at your disposal, too. I'd recommend looking at RubyGems source code to dig much further, since these are poorly documented and undocumented.
