### ISSUE TITLE
Use rbenv with passenger in production?

### ISSUE THREAD

**Issue by ghost** [rbenv/rbenv#98]
So I'm guessing rbenv isn't officially supported by passenger, is it possible for me to use rbenv on an ubuntu server in place of a compiled system ruby / rvm?

**Comment by janekska** [comment]
All links above are broken.
Just a bit stuck on how to tell the passenger to use rbenv...

**Comment by marnen** [comment]
Will pointing Passenger to the rbenv shim be sufficient, or is more necessary?

**Comment by mislav** [comment]
Hi all, please refer to general guidelines at https://github.com/rbenv/rbenv/wiki/Deploying-with-rbenv

Additionally, for Passenger, folks seem to be having luck by setting this in their nginx config:
```
passenger_ruby /home/USER/.rbenv/shims/ruby;.
```

Locking the conversation since this is not a forum to discuss deployment. Most of the time, ensuring that the `~/.rbenv/shims` directory is in PATH solves all problems with other tools "integrating" with rbenv.
