### ISSUE TITLE
Permssions

### ISSUE THREAD

**Issue by uchuugaka** [rbenv/rbenv#990]
So I was getting the often reported permissions issue.
You don't have write permissions for the  /path/to/gems/of/shimmed/version
Even after doing the init and all of that.

```
$ rbenv init
# Load rbenv automatically by appending
# the following to ~/.bash_profile:
eval "$(rbenv init -)"
```

I even added that to the /etc/profile to ensure Bash was definitely loading it.
Started new session to ensure reloading it. 

However, I did find the owner was set to root for ~/.rbenv and its children.
Is that expected?
After making myself owner 
`chown -R my.account ~/.rbenv`
everything works.

Do let me know if this is wrong.

This is on macOS Sierra latest version.

**Comment by mislav** [comment]
The reason why `~/.rbenv` was created as root might have been because you've added the line to `/etc/profile` instead of `~/.bash_profile`. You should only add this to your user configuration files, not the system files (any files in `/etc/`).

However, you've changed the ownership of `~/.rbenv` directory to yourself now, so everything should be fine! 👍
